# Notebook 1 : Découverte de Pandas

In [13]:
import pandas as pd

## Iris

Nous considérons le jeu de données connu sous le nom des [Iris de Fisher](https://fr.wikipedia.org/wiki/Iris_de_Fisher). Répondez aux questions suivantes à l'aide du module Pandas.

1. Charger le jeu de données dans un dataframe `iris` à partir du fichier `iris.csv` et afficher le dataframe.

In [14]:
df=pd.read_csv('data/iris.csv',sep=',')
df.head(10)

   SepalLength  SepalWidth  PetalLength  PetalWidth Species
0          5.1         3.5          1.4         0.2  setosa
1          4.9         3.0          1.4         0.2  setosa
2          4.7         3.2          1.3         0.2  setosa
3          4.6         3.1          1.5         0.2  setosa
4          5.0         3.6          1.4         0.2  setosa
5          5.4         3.9          1.7         0.4  setosa
6          4.6         3.4          1.4         0.3  setosa
7          5.0         3.4          1.5         0.2  setosa
8          4.4         2.9          1.4         0.2  setosa
9          4.9         3.1          1.5         0.1  setosa

2. Sélectionner les variables `PetalWidth` et `Species`.

In [15]:
df[['PetalWidth','Species']]

     PetalWidth    Species
0           0.2     setosa
1           0.2     setosa
2           0.2     setosa
3           0.2     setosa
4           0.2     setosa
..          ...        ...
145         2.3  virginica
146         1.9  virginica
147         2.0  virginica
148         2.3  virginica
149         1.8  virginica

[150 rows x 2 columns]

3. Extraire le sous-dataframe qui contient uniquement les iris des espèces `versicolor` ou `virginica`.

In [16]:
df[(df['Species']=='versicolor')|(df['Species']=='virginica')]

     SepalLength  SepalWidth  PetalLength  PetalWidth     Species
50           7.0         3.2          4.7         1.4  versicolor
51           6.4         3.2          4.5         1.5  versicolor
52           6.9         3.1          4.9         1.5  versicolor
53           5.5         2.3          4.0         1.3  versicolor
54           6.5         2.8          4.6         1.5  versicolor
..           ...         ...          ...         ...         ...
145          6.7         3.0          5.2         2.3   virginica
146          6.3         2.5          5.0         1.9   virginica
147          6.5         3.0          5.2         2.0   virginica
148          6.2         3.4          5.4         2.3   virginica
149          5.9         3.0          5.1         1.8   virginica

[100 rows x 5 columns]

4. Compter le nombre d'iris de l'espèce `setosa`.

In [17]:
len(df[df['Species']=='setosa'])

50

In [23]:
#Autre methode
print(
    df.groupby('Species')
        .agg( # NamedAgg permet de nommer les agrégations
            iris_count=pd.NamedAgg(column="Species", aggfunc="count")
        )
        .sort_values(by="iris_count", ascending=False)
)

            iris_count
Species
setosa              50
versicolor          50
virginica           50

5. Calculer la moyenne de la variable `PetalWidth` pour les iris de l'espèce `versicolor`.

In [25]:
print(df[df['Species']=='versicolor']['PetalWidth'].mean())

1.3259999999999998

6. Ajouter une variable `SumWidth` qui contient la somme des variables `PetalWidth` et `SepalWidth`.

In [27]:
df['SumWidth']=df['PetalWidth']+df['SepalWidth']
df.head(10)

   SepalLength  SepalWidth  PetalLength  PetalWidth Species  SumWidth
0          5.1         3.5          1.4         0.2  setosa       3.7
1          4.9         3.0          1.4         0.2  setosa       3.2
2          4.7         3.2          1.3         0.2  setosa       3.4
3          4.6         3.1          1.5         0.2  setosa       3.3
4          5.0         3.6          1.4         0.2  setosa       3.8
5          5.4         3.9          1.7         0.4  setosa       4.3
6          4.6         3.4          1.4         0.3  setosa       3.7
7          5.0         3.4          1.5         0.2  setosa       3.6
8          4.4         2.9          1.4         0.2  setosa       3.1
9          4.9         3.1          1.5         0.1  setosa       3.2

7. Calculer la moyenne et la variance de la variable `SepalLength` pour chaque espèce.

In [ ]:
print(
    df.groupby('Species')
        .agg( # NamedAgg permet de nommer les agrégations
            SepalWidth_var=pd.NamedAgg(column="SepalLength", aggfunc="mean"),
            SepalLength_moy=pd.NamedAgg(column="SepalLength", aggfunc="var")
        )
)

            SepalLength_var  SepalLength_moy
Species
setosa                5.006         0.124249
versicolor            5.936         0.266433
virginica             6.588         0.404343

8. Calculer la moyenne de toutes les variables pour chaque espèce. Afficher le résultat au format large et au format long.

In [ ]:
#format large
print(
    df.groupby('Species')
        .agg(['mean'])
)

           SepalLength SepalWidth PetalLength PetalWidth SumWidth
                  mean       mean        mean       mean     mean
Species
setosa           5.006      3.428       1.462      0.246    3.674
versicolor       5.936      2.770       4.260      1.326    4.096
virginica        6.588      2.974       5.552      2.026    5.000

In [ ]:
print(
    df['Species']
        .agg(['mean'])
)

## Houston flights

Nous considérons le jeux de données `hflights` relatif à des vols au départ des aéroports *Houston George Bush Intercontinental Airport* (IAH) et *William P. Hobby Airport* (HOU).

1. Charger le jeu de données dans un dataframe `hflights` à partir du fichier `hflights.csv`

In [30]:
df=pd.read_csv('data/hflights.csv',sep=',')
df.head(10)

,Year,Month,DayofMonth,DayOfWeek,DepTime,ArrTime,UniqueCarrier,FlightNum,TailNum,ActualElapsedTime,...,ArrDelay,DepDelay,Origin,Dest,Distance,TaxiIn,TaxiOut,Cancelled,CancellationCode,Diverted
0,2011,1,1,6,1400.0,1500.0,AA,428,N576AA,60.0,...,-10.0,0.0,IAH,DFW,224,7.0,13.0,0,NaN,0
1,2011,1,2,7,1401.0,1501.0,AA,428,N557AA,60.0,...,-9.0,1.0,IAH,DFW,224,6.0,9.0,0,NaN,0
2,2011,1,3,1,1352.0,1502.0,AA,428,N541AA,70.0,...,-8.0,-8.0,IAH,DFW,224,5.0,17.0,0,NaN,0
3,2011,1,4,2,1403.0,1513.0,AA,428,N403AA,70.0,...,3.0,3.0,IAH,DFW,224,9.0,22.0,0,NaN,0
4,2011,1,5,3,1405.0,1507.0,AA,428,N492AA,62.0,...,-3.0,5.0,IAH,DFW,224,9.0,9.0,0,NaN,0
5,2011,1,6,4,1359.0,1503.0,AA,428,N262AA,64.0,...,-7.0,-1.0,IAH,DFW,224,6.0,13.0,0,NaN,0
6,2011,1,7,5,1359.0,1509.0,AA,428,N493AA,70.0,...,-1.0,-1.0,IAH,DFW,224,12.0,15.0,0,NaN,0
7,2011,1,8,6,1355.0,1454.0,AA,428,N477AA,59.0,...,-16.0,-5.0,IAH,DFW,224,7.0,12.0,0,NaN,0
8,2011,1,9,7,1443.0,1554.0,AA,428,N476AA,71.0,...,44.0,43.0,IAH,DFW,224,8.0,22.0,0,NaN,0
9,2011,1,10,1,1443.0,1553.0,AA,428,N504AA,70.0,...,43.0,43.0,IAH,DFW,224,6.0,19.0,0,NaN,0

2. Sélectionner les variable `Dest`, `Distance`, `TaxiIn` et `TaxiOut` avec la méthode `filter`.

In [31]:
print(df.filter(items=["Dest", "Distance",'TaxiIn','TaxiOut']))

       Dest  Distance  TaxiIn  TaxiOut
0       DFW       224     7.0     13.0
1       DFW       224     6.0      9.0
2       DFW       224     5.0     17.0
3       DFW       224     9.0     22.0
4       DFW       224     9.0      9.0
...     ...       ...     ...      ...
227491  TPA       781     5.0     11.0
227492  TPA       781     4.0      9.0
227493  TUL       453     4.0     14.0
227494  TUL       453     3.0      9.0
227495  TUL       453     3.0     11.0

[227496 rows x 4 columns]

3. Sélectionner les variables `DepTime`, `ArrTime`, `ActualElapsedTime` et `AirTime` avec la méthode `filter` et le paramètre `like`.

In [33]:
print(df.filter(regex="Time$"))

        DepTime  ArrTime  ActualElapsedTime  AirTime
0        1400.0   1500.0               60.0     40.0
1        1401.0   1501.0               60.0     45.0
2        1352.0   1502.0               70.0     48.0
3        1403.0   1513.0               70.0     39.0
4        1405.0   1507.0               62.0     44.0
...         ...      ...                ...      ...
227491   1818.0   2111.0              113.0     97.0
227492   2047.0   2334.0              107.0     94.0
227493    912.0   1031.0               79.0     61.0
227494    656.0    812.0               76.0     64.0
227495   1600.0   1713.0               73.0     59.0

[227496 rows x 4 columns]

4. Ajouter une variable `ActualGroundTime` qui correspond à `ActualElapsedTime` moins `AirTime`.

In [36]:
df['ActualGroundTime']=df['ActualElapsedTime']-df['AirTime']
print(df.filter(regex="Time$"))

        DepTime  ArrTime  ActualElapsedTime  AirTime  ActualGroundTime
0        1400.0   1500.0               60.0     40.0              20.0
1        1401.0   1501.0               60.0     45.0              15.0
2        1352.0   1502.0               70.0     48.0              22.0
3        1403.0   1513.0               70.0     39.0              31.0
4        1405.0   1507.0               62.0     44.0              18.0
...         ...      ...                ...      ...               ...
227491   1818.0   2111.0              113.0     97.0              16.0
227492   2047.0   2334.0              107.0     94.0              13.0
227493    912.0   1031.0               79.0     61.0              18.0
227494    656.0    812.0               76.0     64.0              12.0
227495   1600.0   1713.0               73.0     59.0              14.0

[227496 rows x 5 columns]

5. Ajouter une variable `AverageSpeed` qui donne la vitesse moyenne du vol et ordonner la table selon les valeurs décroissantes de cette variable.

In [44]:
df['AverageSpeed']=df['Distance']/df['AirTime']
#print(df[['DepTime','ArrTime','ActualElapsedTime','AirTime','ActualGroundTime','AverageSpeed']])
print(df.filter(regex="Time$").join(df[['AverageSpeed']]))

        DepTime  ArrTime  ActualElapsedTime  AirTime  ActualGroundTime  \
0        1400.0   1500.0               60.0     40.0              20.0
1        1401.0   1501.0               60.0     45.0              15.0
2        1352.0   1502.0               70.0     48.0              22.0
3        1403.0   1513.0               70.0     39.0              31.0
4        1405.0   1507.0               62.0     44.0              18.0
...         ...      ...                ...      ...               ...
227491   1818.0   2111.0              113.0     97.0              16.0
227492   2047.0   2334.0              107.0     94.0              13.0
227493    912.0   1031.0               79.0     61.0              18.0
227494    656.0    812.0               76.0     64.0              12.0
227495   1600.0   1713.0               73.0     59.0              14.0

        AverageSpeed
0           5.600000
1           4.977778
2           4.666667
3           5.743590
4           5.090909
...              ...
227491      8.051546
227492      8.308511
227493      7.426230
227494      7.078125
227495      7.677966

[227496 rows x 6 columns]

6. Sélectionner les vols à destination de `JFK`.

In [46]:
df[df['Dest']=='JFK']

,Year,Month,DayofMonth,DayOfWeek,DepTime,ArrTime,UniqueCarrier,FlightNum,TailNum,ActualElapsedTime,...,Origin,Dest,Distance,TaxiIn,TaxiOut,Cancelled,CancellationCode,Diverted,ActualGroundTime,AverageSpeed
304,2011,1,1,6,654.0,1124.0,B6,620,N324JB,210.0,...,HOU,JFK,1428,6.0,23.0,0,NaN,0,29.0,7.889503
305,2011,1,1,6,1639.0,2110.0,B6,622,N324JB,211.0,...,HOU,JFK,1428,12.0,11.0,0,NaN,0,23.0,7.595745
306,2011,1,2,7,703.0,1113.0,B6,620,N324JB,190.0,...,HOU,JFK,1428,6.0,12.0,0,NaN,0,18.0,8.302326
307,2011,1,2,7,1604.0,2040.0,B6,622,N324JB,216.0,...,HOU,JFK,1428,9.0,31.0,0,NaN,0,40.0,8.113636
308,2011,1,3,1,659.0,1100.0,B6,620,N229JB,181.0,...,HOU,JFK,1428,3.0,12.0,0,NaN,0,15.0,8.602410
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
208752,2011,12,29,4,1541.0,1959.0,B6,622,N206JB,198.0,...,HOU,JFK,1428,7.0,8.0,0,NaN,0,15.0,7.803279
208753,2011,12,30,5,634.0,1040.0,B6,620,N317JB,186.0,...,HOU,JFK,1428,4.0,12.0,0,NaN,0,16.0,8.400000
208754,2011,12,30,5,1541.0,1957.0,B6,622,N296JB,196.0,...,HOU,JFK,1428,5.0,10.0,0,NaN,0,15.0,7.889503
208755,2011,12,31,6,831.0,1251.0,B6,620,N247JB,200.0,...,HOU,JFK,1428,5.0,20.0,0,NaN,0,25.0,8.160000
208756,2011,12,31,6,1544.0,2009.0,B6,622,N323JB,205.0,...,HOU,JFK,1428,4.0,11.0,0,NaN,0,15.0,7.515789

7. Compter le nombre de vols à destination de `JFK`.

In [47]:
len(df[df['Dest']=='JFK'])

695

8. Agréger les données `hflights` pour obtenir :
- `n` : le nombre total de vols,
- `n_dest`: le nombre total de destinations distinctes,
- `n_carrier` : le nombre total de compagnies distinctes.

In [ ]:
df.agg(\
    
    )

9. Agréger les données des vols de la compagnie `AA` pour obtenir :
- le nombre total de vols,
- le nombre total de vols annulés,
- la valeur moyenne de `ArrDelay`.

10. Calculer pour chaque compagnie :
- le nombre total de vols,
- la valeur moyenne de `AirTime`.

11. Ordonner les compagnies en fonction des retards moyens au départ.