# Notebook 1 : Découverte de Pandas

In [13]:
import pandas as pd

## Iris

Nous considérons le jeu de données connu sous le nom des [Iris de Fisher](https://fr.wikipedia.org/wiki/Iris_de_Fisher). Répondez aux questions suivantes à l'aide du module Pandas.

1. Charger le jeu de données dans un dataframe `iris` à partir du fichier `iris.csv` et afficher le dataframe.

In [14]:
df=pd.read_csv('data/iris.csv',sep=',')
df.head(10)

   SepalLength  SepalWidth  PetalLength  PetalWidth Species
0          5.1         3.5          1.4         0.2  setosa
1          4.9         3.0          1.4         0.2  setosa
2          4.7         3.2          1.3         0.2  setosa
3          4.6         3.1          1.5         0.2  setosa
4          5.0         3.6          1.4         0.2  setosa
5          5.4         3.9          1.7         0.4  setosa
6          4.6         3.4          1.4         0.3  setosa
7          5.0         3.4          1.5         0.2  setosa
8          4.4         2.9          1.4         0.2  setosa
9          4.9         3.1          1.5         0.1  setosa

2. Sélectionner les variables `PetalWidth` et `Species`.

In [15]:
df[['PetalWidth','Species']]

     PetalWidth    Species
0           0.2     setosa
1           0.2     setosa
2           0.2     setosa
3           0.2     setosa
4           0.2     setosa
..          ...        ...
145         2.3  virginica
146         1.9  virginica
147         2.0  virginica
148         2.3  virginica
149         1.8  virginica

[150 rows x 2 columns]

3. Extraire le sous-dataframe qui contient uniquement les iris des espèces `versicolor` ou `virginica`.

In [16]:
df[(df['Species']=='versicolor')|(df['Species']=='virginica')]

     SepalLength  SepalWidth  PetalLength  PetalWidth     Species
50           7.0         3.2          4.7         1.4  versicolor
51           6.4         3.2          4.5         1.5  versicolor
52           6.9         3.1          4.9         1.5  versicolor
53           5.5         2.3          4.0         1.3  versicolor
54           6.5         2.8          4.6         1.5  versicolor
..           ...         ...          ...         ...         ...
145          6.7         3.0          5.2         2.3   virginica
146          6.3         2.5          5.0         1.9   virginica
147          6.5         3.0          5.2         2.0   virginica
148          6.2         3.4          5.4         2.3   virginica
149          5.9         3.0          5.1         1.8   virginica

[100 rows x 5 columns]

4. Compter le nombre d'iris de l'espèce `setosa`.

In [17]:
len(df[df['Species']=='setosa'])

50

In [23]:
#Autre methode
print(
    df.groupby('Species')
        .agg( # NamedAgg permet de nommer les agrégations
            iris_count=pd.NamedAgg(column="Species", aggfunc="count")
        )
        .sort_values(by="iris_count", ascending=False)
)

            iris_count
Species
setosa              50
versicolor          50
virginica           50

5. Calculer la moyenne de la variable `PetalWidth` pour les iris de l'espèce `versicolor`.

In [25]:
print(df[df['Species']=='versicolor']['PetalWidth'].mean())

1.3259999999999998

6. Ajouter une variable `SumWidth` qui contient la somme des variables `PetalWidth` et `SepalWidth`.

In [27]:
df['SumWidth']=df['PetalWidth']+df['SepalWidth']
df.head(10)

   SepalLength  SepalWidth  PetalLength  PetalWidth Species  SumWidth
0          5.1         3.5          1.4         0.2  setosa       3.7
1          4.9         3.0          1.4         0.2  setosa       3.2
2          4.7         3.2          1.3         0.2  setosa       3.4
3          4.6         3.1          1.5         0.2  setosa       3.3
4          5.0         3.6          1.4         0.2  setosa       3.8
5          5.4         3.9          1.7         0.4  setosa       4.3
6          4.6         3.4          1.4         0.3  setosa       3.7
7          5.0         3.4          1.5         0.2  setosa       3.6
8          4.4         2.9          1.4         0.2  setosa       3.1
9          4.9         3.1          1.5         0.1  setosa       3.2

7. Calculer la moyenne et la variance de la variable `SepalLength` pour chaque espèce.

In [28]:
print(
    df.groupby('Species')
        .agg( # NamedAgg permet de nommer les agrégations
            SepalLength_var=pd.NamedAgg(column="SepalLength", aggfunc="mean"),
            SepalLength_moy=pd.NamedAgg(column="SepalLength", aggfunc="var")
        )
)

            SepalLength_var  SepalLength_moy
Species
setosa                5.006         0.124249
versicolor            5.936         0.266433
virginica             6.588         0.404343

8. Calculer la moyenne de toutes les variables pour chaque espèce. Afficher le résultat au format large et au format long.

## Houston flights

Nous considérons le jeux de données `hflights` relatif à des vols au départ des aéroports *Houston George Bush Intercontinental Airport* (IAH) et *William P. Hobby Airport* (HOU).

1. Charger le jeu de données dans un dataframe `hflights` à partir du fichier `hflights.csv`

2. Sélectionner les variable `Dest`, `Distance`, `TaxiIn` et `TaxiOut` avec la méthode `filter`.

3. Sélectionner les variables `DepTime`, `ArrTime`, `ActualElapsedTime` et `AirTime` avec la méthode `filter` et le paramètre `like`.

4. Ajouter une variable `ActualGroundTime` qui correspond à `ActualElapsedTime` moins `AirTime`.

5. Ajouter une variable `AverageSpeed` qui donne la vitesse moyenne du vol et ordonner la table selon les valeurs décroissantes de cette variable.

6. Sélectionner les vols à destination de `JFK`.

7. Compter le nombre de vols à destination de `JFK`.

8. Agréger les données `hflights` pour obtenir :
- `n` : le nombre total de vols,
- `n_dest`: le nombre total de destinations distinctes,
- `n_carrier` : le nombre total de compagnies distinctes.

9. Agréger les données des vols de la compagnie `AA` pour obtenir :
- le nombre total de vols,
- le nombre total de vols annulés,
- la valeur moyenne de `ArrDelay`.

10. Calculer pour chaque compagnie :
- le nombre total de vols,
- la valeur moyenne de `AirTime`.

11. Ordonner les compagnies en fonction des retards moyens au départ.