# Notebook 5 : Web scraping

In [13]:
# Décommenter la ligne suivante pour installer lxml (nécessaire pour read_html)
#%pip install lxml

In [14]:
import pandas as pd
import requests

from bs4 import BeautifulSoup

## Bonsaïs

Le site [Umi Zen Bonsai](https://umizenbonsai.com/) est une boutique de vente en ligne dédiée aux bonsaïs. Les conifères sont disponible sur la page web [https://umizenbonsai.com/shop/bonsai/coniferes/](https://umizenbonsai.com/shop/bonsai/coniferes/). Comme beaucoup d'autres sites, l'information est organisée en blocs dans lesquels il est possible de récupérer des données.

Pour scraper ce type de site, le processus consiste à capturer les blocs dans un premier temps, puis à en extraire les données.

1. Récupérer le contenu de la page avec `requests` et passer le résultat au parser de `BeautifulSoup`.

In [15]:
base_url = "https://umizenbonsai.com/shop/bonsai/coniferes/"
page_url=""

url=base_url+page_url

r=requests.get(url)
r.raise_for_status()

print(r.text[:800] + "...")

<!DOCTYPE html>
<html class="html" lang="fr-FR">
<head>
	<meta charset="UTF-8">
	<link rel="profile" href="https://gmpg.org/xfn/11">

	<meta name='robots' content='index, follow, max-image-preview:large, max-snippet:-1, max-video-preview:-1' />
<link rel="preload" as="font" href="https://fonts.gstatic.com/s/montserrat/v26/JTUQjIg1_i6t8kCHKm459WxRyS7m0dR9pA.woff2" data-wpacu-preload-google-font="1" crossorigin>
<link rel="preload" as="font" href="https://fonts.gstatic.com/s/montserrat/v26/JTUSjIg1_i6t8kCHKm459WlhyyTh89Y.woff2" data-wpacu-preload-google-font="1" crossorigin>
<link rel="preload" as="font" href="https://fonts.gstatic.com/s/montserrat/v26/JTUSjIg1_i6t8kCHKm459Wlhyw.woff2" data-wpacu-preload-google-font="1" crossorigin>
<meta name="viewport" content="width=device-width, initial-...

In [16]:
soup = BeautifulSoup(r.text, "html.parser") # HTML parser de Python
print(str(soup)[:700] + "...")

<!DOCTYPE html>

<html class="html" lang="fr-FR">
<head>
<meta charset="utf-8"/>
<link href="https://gmpg.org/xfn/11" rel="profile"/>
<meta content="index, follow, max-image-preview:large, max-snippet:-1, max-video-preview:-1" name="robots">
<link as="font" crossorigin="" data-wpacu-preload-google-font="1" href="https://fonts.gstatic.com/s/montserrat/v26/JTUQjIg1_i6t8kCHKm459WxRyS7m0dR9pA.woff2" rel="preload"/>
<link as="font" crossorigin="" data-wpacu-preload-google-font="1" href="https://fonts.gstatic.com/s/montserrat/v26/JTUSjIg1_i6t8kCHKm459WlhyyTh89Y.woff2" rel="preload"/>
<link as="font" crossorigin="" data-wpacu-preload-google-font="1" href="https://fonts.gstatic.com/s/montserrat/v26/...

2. Écrire un sélecteur CSS pour capturer les éléments `li` qui contiennent les blocs correspondants aux bonsaïs. Vérifier sur le site que le nombre de bonsaïs affichés correspond.

In [19]:
css_selector = "ul.products li.entry"
bonsai= soup.select(css_selector)

print('nb objet '+str(len(bonsai)))

nb objet 5

In [21]:
print(bonsai[0])

<li class="entry has-media col span_1_of_4 owp-content-center owp-thumbs-layout-horizontal owp-btn-big owp-tabs-layout-horizontal circle-sale product type-product post-55126 status-publish first instock product_cat-coniferes product_cat-tous-les-bonsai product_tag-bonsai has-post-thumbnail taxable shipping-taxable product-type-simple">
<div class="product-inner clr">
<div class="woo-entry-image clr">
<a class="woocommerce-LoopProduct-link" href="https://umizenbonsai.com/vente/bonsai-cypres-du-japon/"><img alt="Bonsai Cyprès du Japon – 33cm" class="woo-entry-image-main" decoding="async" fetchpriority="high" height="800" itemprop="image" sizes="(max-width: 800px) 100vw, 800px" src="https://umizenbonsai.com/wp-content/uploads/bonsai-cypres-du-japon-umi-zen-bonsai-shop.jpg" srcset="https://umizenbonsai.com/wp-content/uploads/bonsai-cypres-du-japon-umi-zen-bonsai-shop.jpg 800w, https://umizenbonsai.com/wp-content/uploads/bonsai-cypres-du-japon-umi-zen-bonsai-shop-150x150.jpg 150w, https://umizenbonsai.com/wp-content/uploads/bonsai-cypres-du-japon-umi-zen-bonsai-shop-300x300.jpg 300w, https://umizenbonsai.com/wp-content/uploads/bonsai-cypres-du-japon-umi-zen-bonsai-shop-768x768.jpg 768w, https://umizenbonsai.com/wp-content/uploads/bonsai-cypres-du-japon-umi-zen-bonsai-shop-600x600.jpg 600w, https://umizenbonsai.com/wp-content/uploads/bonsai-cypres-du-japon-umi-zen-bonsai-shop-100x100.jpg 100w, https://umizenbonsai.com/wp-content/uploads/bonsai-cypres-du-japon-umi-zen-bonsai-shop-64x64.jpg 64w" width="800"/></a> </div><!-- .woo-entry-image -->
<ul class="woo-entry-inner clr"><li class="image-wrap">
<div class="woo-entry-image clr">
<a class="woocommerce-LoopProduct-link" href="https://umizenbonsai.com/vente/bonsai-cypres-du-japon/"><img alt="Bonsai Cyprès du Japon – 33cm" class="woo-entry-image-main" decoding="async" height="800" itemprop="image" sizes="(max-width: 800px) 100vw, 800px" src="https://umizenbonsai.com/wp-content/uploads/bonsai-cypres-du-japon-umi-zen-bonsai-shop.jpg" srcset="https://umizenbonsai.com/wp-content/uploads/bonsai-cypres-du-japon-umi-zen-bonsai-shop.jpg 800w, https://umizenbonsai.com/wp-content/uploads/bonsai-cypres-du-japon-umi-zen-bonsai-shop-150x150.jpg 150w, https://umizenbonsai.com/wp-content/uploads/bonsai-cypres-du-japon-umi-zen-bonsai-shop-300x300.jpg 300w, https://umizenbonsai.com/wp-content/uploads/bonsai-cypres-du-japon-umi-zen-bonsai-shop-768x768.jpg 768w, https://umizenbonsai.com/wp-content/uploads/bonsai-cypres-du-japon-umi-zen-bonsai-shop-600x600.jpg 600w, https://umizenbonsai.com/wp-content/uploads/bonsai-cypres-du-japon-umi-zen-bonsai-shop-100x100.jpg 100w, https://umizenbonsai.com/wp-content/uploads/bonsai-cypres-du-japon-umi-zen-bonsai-shop-64x64.jpg 64w" width="800"/></a> </div><!-- .woo-entry-image -->
</li><li class="price-wrap">
<span class="price"><span class="woocommerce-Price-amount amount"><bdi>150.00<span class="woocommerce-Price-currencySymbol">€</span></bdi></span></span>
</li><li class="btn-wrap clr"><a aria-describedby="woocommerce_loop_add_to_cart_link_describedby_55126" aria-label="En savoir plus sur “Bonsai Cyprès du Japon - 33cm”" class="button product_type_simple" data-product_id="55126" data-product_sku="" data-quantity="1" data-success_message="" href="https://umizenbonsai.com/vente/bonsai-cypres-du-japon/" rel="nofollow">Retrait à Hossegor</a> <span class="screen-reader-text" id="woocommerce_loop_add_to_cart_link_describedby_55126">
</span>
</li><li class="title"><h2><a href="https://umizenbonsai.com/vente/bonsai-cypres-du-japon/">Bonsai Cyprès du Japon – 33cm</a></h2></li><li class="rating"></li></ul></div><!-- .product-inner .clr --></li>

In [22]:
print(bonsai[0].select('li.price-wrap bdi'))

[<bdi>150.00<span class="woocommerce-Price-currencySymbol">€</span></bdi>]

In [25]:
print(bonsai[0].select('li.price-wrap bdi')[0].text)

150.00€

In [27]:
print(bonsai[0].select('li.price-wrap bdi')[0].text[:-1])

150.00

3. Écrire une fonction qui prend un bloc de la liste précédente et retourne un tuple contenant le nom, le prix et le lien de description du bonsaï.

In [ ]:
#tentative recuperation du nom
print(bonsai[0].select('li.title a'))

[<a href="https://umizenbonsai.com/vente/bonsai-cypres-du-japon/">Bonsai Cyprès du Japon – 33cm</a>]

In [30]:
print(bonsai[0].select('li.title a')[0].text)

Bonsai Cyprès du Japon – 33cm

In [31]:
#recuperation lien
print(bonsai[0].select('li.title a')[0].attrs('href'))

TypeError: 'AttributeDict' object is not callable

In [35]:
def bonsai_data(bonsai):
    bonsai_a=bonsai.select('li.title a')[0]
    nom=bonsai_a.text
    url=bonsai_a.attrs['href']
    prix_str=bonsai.select('li.price-wrap bdi')[0].text
    return {'nom':nom,'url':url,'prix':prix_str}

In [39]:
bonsai_df=pd.DataFrame([bonsai_data(b) for b in bonsai])

bonsai_df.head(10)

,nom,url,prix
0,Bonsai Cyprès du Japon – 33cm,https://umizenbonsai.com/vente/bonsai-cypres-d...,150.00€
1,Bonsai Genévrier de Phénicie – 67cm,https://umizenbonsai.com/vente/bonsai-genevrie...,450.00€
2,Bonsai If Commun – 38cm,https://umizenbonsai.com/vente/bonsai-if-commu...,450.00€
3,Bonsai If Commun – 58cm,https://umizenbonsai.com/vente/bonsai-if-commu...,"1,350.00€"
4,Bonsai Pin Sylvestre – 38cm,https://umizenbonsai.com/vente/bonsai-pin-sylv...,"1,250.00€"

4. Utiliser les deux questions précédentes pour construire un dataframe contenant les données des bonsaïs.

5. (*Bonus*) Écrire une fonction pour récupérer la provenance, le feuilage et les dimension du bonsaï à partir du lien de description. Utiliser cette fonction pour ajouter des colonnes au dataframe précédent

## Trampoline

Le trampoline est un sport olympique depuis les jeux de Sydney en 2000. La page suivante contient les listes des hommes et des femmes ayant obtenu une médaille olympique dans cette discipline :
[https://fr.wikipedia.org/wiki/Liste_des_m%C3%A9daill%C3%A9s_olympiques_au_trampoline](https://fr.wikipedia.org/wiki/Liste_des_m%C3%A9daill%C3%A9s_olympiques_au_trampoline)

Un tableau est contenu dans un élément `table` avec des balises pour les lignes `tr`, pour les colonnes `th`, pour les cellules `td`, ... Cela peut être fastidieux à scraper et très répétitif. Heureusement, Pandas propose la fonction `read_html` pour récupérer des tableaux sous forme de dataframes à partir d'une page web.

1. Récupérer le contenu de la page des médaillés olympiques au trampoline avec `requests` en passant un *User Agent* dans les en-têtes `headers`. Utiliser ensuite la fonction `read_html` de Pandas directement sur le contenu textuel de la page. Combien de dataframes sont récupérés ?

2. Extraire de la liste précédente les dataframes des médailles masculines et féminines.

3. À partir de ces dataframes, compter combien chaque pays a reçu de médailles d'or, d'argent et de bronze.

4. (*Bonus*) Construire un dataframe contenant, pour chaque pays, le nombre de médailles d'or, d'argent et de bronze ainsi que le nombre total de médailles. Classer ce dataframe dans l'ordre usuel en fonction d'abord du nombre de médailles d'or, puis du nombre de médailles d'argent et enfin du nombre de médailles de bronze. Comparer le résultat avec le tableau des médailles sur la page [https://fr.wikipedia.org/wiki/Trampoline_aux_Jeux_olympiques](https://fr.wikipedia.org/wiki/Trampoline_aux_Jeux_olympiques).

## Cate Blanchett

Dans le cours, nous avons essayé de trouver avec quels acteurs Cate Blanchett a joué le plus au cours des années 2000. Pour cela, nous avons récupéré la liste des pages Wikipedia des films où elle tient un rôle avec le code suivant :

In [32]:
url_wikipedia = "https://fr.wikipedia.org"
url_blanchett = url_wikipedia + "/wiki/Cate_Blanchett"

# Ne pas oublier le User Agent pour les pages Wikipedia
r_blanchett = requests.get(url_blanchett, headers={"User-Agent": "CepeBot"})
assert r_blanchett.status_code == 200, f"Erreur {r_blanchett.status_code}"

soup_blanchett = BeautifulSoup(r_blanchett.text, "html.parser")

selector_films = "#mw-content-text div ul:nth-of-type(3) li i a"
films_blanchett = soup_blanchett.select(selector_films)

films_data = [
    {
        "titre": film.attrs["title"],
        "url_wikipedia": url_wikipedia + film.attrs["href"]
    }
    for film in films_blanchett
    if not (
        film.attrs.get("class") == ["new"] # Film sans page
        or film.attrs["title"] == "Galadriel" # Mauvais lien
    )
]

films = pd.DataFrame(films_data)

films

,titre,url_wikipedia
0,Les Larmes d'un homme,https://fr.wikipedia.org/wiki/Les_Larmes_d%27u...
1,Intuitions,https://fr.wikipedia.org/wiki/Intuitions
2,"Bandits (film, 2001)","https://fr.wikipedia.org/wiki/Bandits_(film,_2..."
3,Le Seigneur des anneaux : La Communauté de l'a...,https://fr.wikipedia.org/wiki/Le_Seigneur_des_...
4,Charlotte Gray,https://fr.wikipedia.org/wiki/Charlotte_Gray
5,Terre Neuve (film),https://fr.wikipedia.org/wiki/Terre_Neuve_(film)
6,"Heaven (film, 2002)","https://fr.wikipedia.org/wiki/Heaven_(film,_2002)"
7,Le Seigneur des anneaux : Les Deux Tours,https://fr.wikipedia.org/wiki/Le_Seigneur_des_...
8,Veronica Guerin (film),https://fr.wikipedia.org/wiki/Veronica_Guerin_...
9,Coffee and Cigarettes,https://fr.wikipedia.org/wiki/Coffee_and_Cigar...
10,Les Disparues,https://fr.wikipedia.org/wiki/Les_Disparues
11,Le Seigneur des anneaux : Le Retour du roi,https://fr.wikipedia.org/wiki/Le_Seigneur_des_...
12,La Vie aquatique,https://fr.wikipedia.org/wiki/La_Vie_aquatique
13,Aviator,https://fr.wikipedia.org/wiki/Aviator
14,"Little Fish (film, 2005)",https://fr.wikipedia.org/wiki/Little_Fish_(fil...
15,"Babel (film, 2006)","https://fr.wikipedia.org/wiki/Babel_(film,_2006)"
16,The Good German,https://fr.wikipedia.org/wiki/The_Good_German
17,Chronique d'un scandale,https://fr.wikipedia.org/wiki/Chronique_d%27un...
18,Hot Fuzz,https://fr.wikipedia.org/wiki/Hot_Fuzz
19,I'm Not There,https://fr.wikipedia.org/wiki/I%27m_Not_There
20,Elizabeth : L'Âge d'or,https://fr.wikipedia.org/wiki/Elizabeth_:_L%27...
21,Ponyo sur la falaise,https://fr.wikipedia.org/wiki/Ponyo_sur_la_fal...
22,Indiana Jones et le Royaume du crâne de cristal,https://fr.wikipedia.org/wiki/Indiana_Jones_et...
23,L'Étrange Histoire de Benjamin Button (film),https://fr.wikipedia.org/wiki/L%27%C3%89trange...

Le sélecteur CSS que nous avons utilisé ne permettait pas d'obtenir la réponse à notre question car il ne capturait pas toutes les listes d'acteurs (organisation différente pour *Coffee and Cigarettes*, double colonne pour *Aviator*, ...). En effet, les pages Wikipedia des films ne sont pas uniformes et il n'est pas possible d'extraire la distribution de tous les films avec le même sélecteur.

Pour remédier à cela, nous proposons ici d'aller scraper la liste des acteurs sur le site [TMDB](https://www.themoviedb.org/) (*The Movie Database*) dont les pages obéissent toutes à la même organisation. Les pages Wikipedia relatives à des films contiennent toutes un lien externe vers ce site.

1. Pour chaque film, scraper la page Wikipedia pour récupérer le lien vers la page TMDB associée et déduire le lien du casting complet qui ser ajouté le dans une nouvelle colonne du dataframe `films`.

In [34]:
url=films.iat[3, 1]
print(url)

https://fr.wikipedia.org/wiki/Le_Seigneur_des_anneaux_:_La_Communaut%C3%A9_de_l%27anneau

In [40]:
r=requests.get(url, headers={"User-Agent": "CepeBot_EC"})
r.raise_for_status()
soup = BeautifulSoup(r.text, "html.parser") # HTML parser de Python
print(str(soup)[:300] + "...")

<!DOCTYPE html>

<html class="client-nojs vector-feature-language-in-header-enabled vector-feature-language-in-main-menu-disabled vector-feature-language-in-main-page-header-disabled vector-feature-page-tools-pinned-disabled vector-feature-toc-pinned-clientpref-1 vector-feature-main-menu-pinned-disa...

In [43]:
#css_selector
link_list_tmdb= soup.select('a.external')

for elem in link_list_tmdb:
    print(elem)

<a class="external text" href="https://fr.wikipedia.org/w/index.php?title=Le_Seigneur_des_anneaux_:_La_Communaut%C3%A9_de_l%27anneau&amp;action=edit">modifier</a>
<a class="external text" href="https://fr.wikipedia.org/w/index.php?title=Le_Seigneur_des_anneaux_:_La_Communaut%C3%A9_de_l%27anneau&amp;action=edit">modifier</a>
<a class="external text" href="http://www.filmdeculte.com/cinema/film/Seigneur-des-anneaux-La-Communaute-de-lanneau-Le-1373.html" rel="nofollow"><cite style="font-style:normal;">Seigneur des anneaux : La Communauté de l'anneau (Le)</cite></a>
<a class="external text" href="https://voiretmanger.fr/seigneur-anneaux-communaute-anneau-jackson/" rel="nofollow"><cite style="font-style:normal;">Le Seigneur des anneaux : la Communauté de l’anneau, Peter Jackson</cite></a>
<a class="external text" href="https://www.avcesar.com/test/bluray/id-602/le-seigneur-des-anneaux-la-communaute-de-lanneau.html" rel="nofollow"><cite style="font-style:normal;">Le seigneur des anneaux : la communauté de l'anneau</cite></a>
<a class="external text" href="https://www.boxofficemojo.com/movies/?id=fellowshipofthering.htm" rel="nofollow"><cite lang="en" style="font-style:normal;"><span class="lang-en" lang="en"><i>The Lord of the Rings: The Fellowship of the Ring</i></span></cite></a>
<a class="external text" href="http://www.allodoublage.com/glossaire/definition.php?val=160_seigneur+anneaux+-+communaute+anneau" rel="nofollow"><cite style="font-style:normal;">Fiche du doublage français du film</cite></a>
<a class="external text" href="https://www.rsdoublage.com/film-2405-Le-seigneur-des-Anneaux---La-communaut%C3%A9-de-l%27anneau.html" rel="nofollow"><cite style="font-style:normal;">Fiche du doublage français du film</cite></a>
<a class="external text" href="https://trekmovie.com/2008/03/09/new-york-con-reports-pictures-and-video/#more-1711" rel="nofollow"><cite lang="en" style="font-style:normal;">New York Con Reports</cite></a>
<a class="external text" href="https://www.theonering.net/torwp/1999/10/15/21940-daniel-day-lewis-offered-role-of-aragorn-again/" rel="nofollow"><cite lang="en" style="font-style:normal;">Daniel Day-Lewis Offered role of Aragorn, Again!</cite></a>
<a class="external text" href="https://www.mtv.com/news/articles/1576048/will-smith-more-share-movies-that-got-away.jhtml" rel="nofollow"><cite lang="en" style="font-style:normal;">Will Smith Snagged 'I Am Legend' From Schwarzenegger, But Can You Imagine Nicolas Cage In 'The Matrix'?</cite></a>
<a class="external text" href="https://www.birminghammail.co.uk/whats-on/theatre-news/whos-that-playing-the-mikado-69575" rel="nofollow"><cite lang="en" style="font-style:normal;">Who’s that playing The Mikado?</cite></a>
<a class="external text" href="http://www.allmusic.com/album/the-lord-of-the-rings-the-fellowship-of-the-ring-original-motion-picture-soundtrack-r559369" rel="nofollow"><cite lang="en" style="font-style:normal;"><i>The Lord of the Rings: The Fellowship of the Ring</i> - Original Motion Picture Soundtrack</cite></a>
<a class="external text" href="https://www.discogs.com/Howard-Shore-The-Lord-Of-The-Rings-The-Fellowship-Of-The-Ring-The-Complete-Recordings/release/779652" rel="nofollow"><cite lang="en" style="font-style:normal;">Howard Shore – The Lord Of The Rings: The Fellowship Of The Ring - The Complete Recordings</cite></a>
<a class="external text" href="http://www.boxofficemojo.com/yearly/chart/?view2=worldwide&amp;yr=2001&amp;p=.htm" rel="nofollow"><cite lang="en" style="font-style:normal;">2001 Worldwide Grosses</cite></a>
<a class="external text" href="https://lumiere.obs.coe.int/web/film_info/?id=17253" rel="nofollow"><cite style="font-style:normal;"><i>Le Seigneur des anneaux : La Communauté de l'anneau</i></cite></a>
<a class="external text" href="https://www.jpbox-office.com/fichfilm.php?id=2078" rel="nofollow"><cite style="font-style:normal;">Le Seigneur des anneaux : La Communauté de l'anneau</cite></a>
<a class="external text" href="http://www.boxofficemojo.com/movies/?page=intl&amp;id=fellowshipofthering.htm" rel="nofollow"><cite lang="en" style="font-style:normal;"><span class="lang-en" lang="en"><i>The Lord of the Rings: The Fellowship of the Ring</i> Foreign</span></cite></a>
<a class="external text" href="https://www.rottentomatoes.com/m/lord_of_the_rings_the_fellowship_of_the_ring/#!reviews=all" rel="nofollow"><cite lang="en" style="font-style:normal;"><i>The Lord of the Rings - The Fellowship of the Ring</i></cite></a>
<a class="external text" href="https://www.metacritic.com/movie/the-lord-of-the-rings-the-fellowship-of-the-ring" rel="nofollow"><cite lang="en" style="font-style:normal;"><i>The Lord of the Rings - The Fellowship of the Ring</i></cite></a>
<a class="external text" href="https://www.allocine.fr/film/revuedepresse_gen_cfilm=27070.html" rel="nofollow"><cite style="font-style:normal;"><i>Le Seigneur des anneaux : La Communauté de l'anneau</i> - Critiques Presse</cite></a>
<a class="external text" href="http://www.afi.com/100years/movies10.aspx" rel="nofollow"><cite lang="en" style="font-style:normal;">AFI's 100 Years… 100 Movies</cite></a>
<a class="external text" href="https://www.afi.com/10top10/category.aspx?cat=6" rel="nofollow"><cite lang="en" style="font-style:normal;">AFI's Top 10 Fantasy</cite></a>
<a class="external text" href="http://www.empireonline.com/500/92.asp" rel="nofollow"><cite lang="en" style="font-style:normal;"><span class="lang-en" lang="en">The 500 Greatest Movies of All Time</span></cite></a>
<a class="external text" href="https://www.imdb.com/title/tt0120737/" rel="nofollow"><cite style="font-style:normal;"><i>Le Seigneur des anneaux : La Communauté de l'anneau</i></cite></a>
<a class="external text" href="http://rogerebert.suntimes.com/apps/pbcs.dll/article?AID=/20011219/REVIEWS/112190301/1023" rel="nofollow"><cite lang="en" style="font-style:normal;"><i>Lord of the Rings: The Fellowship of the Ring</i></cite></a>
<a class="external text" href="https://www.usatoday.com/life/movies/rings/2001-12-19-rings-review.htm" rel="nofollow"><cite lang="en" style="font-style:normal;">Middle-earth leaps to life in enchanting, violent film</cite></a>
<a class="external text" href="https://movies.nytimes.com/movie/review?_r=2&amp;res=9504EEDE153EF93AA25751C1A9679C8B63&amp;partner=Rotten%20Tomatoes" rel="nofollow"><cite lang="en" style="font-style:normal;">Hit the Road, Middle-Earth Gang</cite></a>
<a class="external text" href="http://www.ew.com/ew/article/0,,187102~1~0~lordofringsfellowship,00.html" rel="nofollow"><cite lang="en" style="font-style:normal;"><i>The Lord of the Rings - The Fellowship of the Ring</i></cite></a>
<a class="external text" href="https://www.lemonde.fr/archives/article/2001/12/18/le-mythe-du-seigneur-des-anneaux-prend-corps-a-l-ecran_4219770_1819218.html?xtmc=la_communaute_de_l_anneau&amp;xtcr=113" rel="nofollow"><cite style="font-style:normal;">Le mythe du « Seigneur des anneaux » prend corps à l'écran</cite></a>
<a class="external text" href="https://www.washingtonpost.com/ac2/wp-dyn/A62431-2001Dec18" rel="nofollow"><cite lang="en" style="font-style:normal;">Frodo Lives! A Spirited 'Lord of the Rings'</cite></a>
<a class="external text" href="http://www.time.com/time/world/article/0,8599,188807,00.html" rel="nofollow"><cite lang="en" style="font-style:normal;">Lord of the Films</cite></a>
<a class="external text" href="http://archives.lesoir.be/le-seigneur-des-anneaux-le-mythe-mis-en-image_t-20011219-Z0LA35.html?queryand=la+communaut%E9+de+l%27anneau&amp;firstHit=50&amp;by=50&amp;when=-1&amp;sort=dateasc&amp;pos=54&amp;all=134&amp;nav=1" rel="nofollow"><cite style="font-style:normal;">Le seigneur des anneaux, le mythe mis en image</cite></a>
<a class="external text" href="http://www.guardian.co.uk/film/2001/dec/14/lordoftherings1" rel="nofollow"><cite lang="en" style="font-style:normal;">A heavyweight cast and a brilliantly realised Middle Earth can't save the adventures of the winsome hobbit</cite></a>
<a class="external text" href="http://www.villagevoice.com/2001-12-18/film/plastic-fantastic/1/" rel="nofollow"><cite lang="en" style="font-style:normal;">Plastic Fantastic</cite></a>
<a class="external text" href="https://www.telerama.fr/cinema/films/le-seigneur-des-anneaux-la-communaute-de-l-anneau,57811,critique.php" rel="nofollow"><cite style="font-style:normal;"><i>Le Seigneur des anneaux : La Communauté de l'anneau</i></cite></a>
<a class="external text" href="https://www.imdb.com/title/tt0120737/awards" rel="nofollow"><cite lang="en" style="font-style:normal;">Awards for <i>Le Seigneur des anneaux : La Communauté de l'anneau</i></cite></a>
<a class="external text" href="https://www.oscars.org/oscars/ceremonies/2002" rel="nofollow"><cite lang="en" style="font-style:normal;">74th Oscars Ceremony</cite></a>
<a class="external text" href="http://awards.bafta.org/award/2002/film" rel="nofollow"><cite lang="en" style="font-style:normal;">BAFTA Awards 2002</cite></a>
<a class="external text" href="https://www.saturnawards.org/The-Saturn-Awards-Past-Winners.php" rel="nofollow"><cite lang="en" style="font-style:normal;">Past Saturn Awards Winners</cite></a>
<a class="external text" href="https://www.imdb.com/event/ev0000296/2002/1" rel="nofollow"><cite lang="en" style="font-style:normal;">6th Annual SATELLITE™ Awards</cite></a>
<a class="external text" href="https://www.thehugoawards.org/hugo-history/2002-hugo-awards/" rel="nofollow"><cite lang="en" style="font-style:normal;">2002 Hugo Awards</cite></a>
<a class="external text" href="http://www.mtv.com/ontv/movieawards/2002/" rel="nofollow"><cite lang="en" style="font-style:normal;">2002 MTV Movie Awards</cite></a>
<a class="external text" href="https://www.sagawards.org/awards/nominees-and-recipients/8th-annual-screen-actors-guild-awards" rel="nofollow"><cite lang="en" style="font-style:normal;">8th Annual Screen Actors Guild Awards</cite></a>
<a class="external text" href="https://www.filmaffinity.com/en/awards.php?award_id=critics_choice_awards&amp;year=2001" rel="nofollow"><cite lang="en" style="font-style:normal;">7th Critics Choice Movie Awards</cite></a>
<a class="external text" href="https://www.imdb.com/event/ev0000464/2001/1" rel="nofollow"><cite lang="en" style="font-style:normal;">2001 NBR Awards</cite></a>
<a class="external text" href="http://www.chlotrudis.org/awards/archives/eighth/index.html" rel="nofollow"><cite lang="en" style="font-style:normal;">8th Annual Chlotrudis Awards</cite></a>
<a class="external text" href="http://www.worldsoundtrackacademy.com/awards2.cgi?go=history&amp;category=&amp;year=2002&amp;type=" rel="nofollow"><cite lang="en" style="font-style:normal;">2002 World Soundtrack Academy Awards</cite></a>
<a class="external text" href="http://www.grammy.com/nominees/search?artist=Howard+Shore&amp;title=&amp;year=2002&amp;genre=All" rel="nofollow"><cite lang="en" style="font-style:normal;">45th Annual Grammy Awards</cite></a>
<a class="external text" href="https://www.sfadb.com/Nebula_Awards_2003" rel="nofollow"><cite lang="en" style="font-style:normal;">2003 Nebula Awards</cite></a>
<a class="external text" href="https://www.goldenglobes.com/browse/film/25391" rel="nofollow"><cite lang="en" style="font-style:normal;">Award Search - The Lord of the Rings: The Fellowship of the Ring</cite></a>
<a class="external text" href="https://www.sfadb.com/Bram_Stoker_Awards_2002" rel="nofollow"><cite lang="en" style="font-style:normal;">2002 Bram Stoker Awards</cite></a>
<a class="external text" href="https://www.commeaucinema.com/film/le-seigneur-des-anneaux-la-communaute-de-l-anneau,3981" rel="nofollow"><cite style="font-style:normal;"><i>Le Seigneur des anneaux : La Communauté de l'anneau</i> - Édition double</cite></a>
<a class="external text" href="https://www.ecranlarge.com/dvd-blu-ray/test/890439-test-seigneur-des-anneaux-le-la-communaute-de-l-anneau-version-longue-4-dvd" rel="nofollow"><cite style="font-style:normal;"><i>Le Seigneur des anneaux : La Communauté de l'anneau</i> - DVD Version longue</cite></a>
<a class="external text" href="http://www.ecranlarge.com/dvd_review-list-9407.php" rel="nofollow"><cite style="font-style:normal;"><i>Le Seigneur des anneaux : La Communauté de l'anneau</i> - Blu-ray</cite></a>
<a class="external text" href="https://cinema.jeuxactu.com/news-hd-le-seigneur-des-anneaux-version-longue-la-date-de-sortie-francaise-13904.htm" rel="nofollow"><cite style="font-style:normal;">Le Seigneur des Anneaux version longue : la date de sortie française</cite></a>
<a class="external text" href="https://www.ecran-miroir.fr/article-blu-ray-la-communaute-de-l-anneau-version-longue-78552193.html" rel="nofollow"><cite style="font-style:normal;">[blu-ray] La Communauté de l'Anneau, version longue</cite></a>
<a class="external text" href="https://www.warnerbros.com/movies/lord-rings-fellowship-ring/" rel="nofollow">Site officiel</a>
<a class="external text" href="https://www.allmovie.com/movie/v255996" rel="nofollow"><span class="lang-en" lang="en">AllMovie</span></a>
<a class="external text" href="https://www.allocine.fr/film/fichefilm_gen_cfilm=27070.html" rel="nofollow">Allociné</a>
<a class="external text" href="https://catalog.afi.com/Catalog/moviedetails/53926" rel="nofollow"><span class="lang-en" lang="en">American Film Institute</span></a>
<a class="external text" href="https://www.cnc.fr/professionnels/visas-et-classification/104293" rel="nofollow">Centre national du cinéma et de l'image animée</a>
<a class="external text" href="https://www.cinematografo.it/pls/cinematografo/consultazione.redirect?sch=40426" rel="nofollow"><span class="lang-it" lang="it">Cinematografo.it</span></a>
<a class="external text" href="http://collections.cinematheque.qc.ca/recherche/oeuvres/fiche/56456" rel="nofollow">Cinémathèque québécoise</a>
<a class="external text" href="https://wikidata-externalid-url.toolforge.org/?p=345&amp;url_prefix=https://www.imdb.com/&amp;id=tt0120737"><span class="lang-en" lang="en">IMDb</span></a>
<a class="external text" href="https://lumiere.obs.coe.int/movie/17253" rel="nofollow">LUMIERE</a>
<a class="external text" href="https://www.mrqe.com/movie_reviews/the-lord-of-the-rings-the-fellowship-of-the-ring-m100000890" rel="nofollow"><span class="lang-en" lang="en">Movie Review Query Engine</span></a>
<a class="external text" href="https://www.nzonscreen.com/title/the-lord-of-the-rings-the-fellowship-of-the-ring-2001" rel="nofollow"><span class="lang-en" lang="en">NZ On Screen</span></a>
<a class="external text" href="https://www.ofdb.de/film/5462," rel="nofollow"><span class="lang-de" lang="de">OFDb</span></a>
<a class="external text" href="https://www.rottentomatoes.com/m/the_lord_of_the_rings_the_fellowship_of_the_ring" rel="nofollow"><span class="lang-en" lang="en">Rotten Tomatoes</span></a>
<a class="external text" href="https://www.themoviedb.org/movie/120" rel="nofollow"><span class="lang-en" lang="en">The Movie Database</span></a>
<a class="external text" href="https://www.moma.org/collection/works/128425" rel="nofollow"><span class="lang-en" lang="en">Museum of Modern Art</span></a>
<a class="external text" href="https://www.metacritic.com/movie/the-lord-of-the-rings-the-fellowship-of-the-ring" rel="nofollow"><span class="lang-en" lang="en">Metacritic</span></a>
<a class="external text" href="https://comicvine.gamespot.com/wd/4025-321/" rel="nofollow"><span class="lang-en" lang="en">Comic Vine</span></a>
<a class="external text" href="https://www.britannica.com/topic/The-Lord-of-the-Rings-The-Fellowship-of-the-Ring" rel="nofollow"><i>Britannica</i></a>
<a class="external text" href="https://www.larousse.fr/encyclopedie/film/le_Seigneur_des_anneaux_la_Communaut%C3%A9_de_lanneau/8834" rel="nofollow"><i>Larousse</i></a>
<a class="external text" href="https://viaf.org/viaf/230337709" rel="nofollow">VIAF</a>
<a class="external text" href="https://id.loc.gov/authorities/n2001027409" rel="nofollow">LCCN</a>
<a class="external text" href="https://d-nb.info/gnd/4675753-3" rel="nofollow">GND</a>
<a class="external text" href="https://www.nli.org.il/en/authorities/987007289807405171" rel="nofollow">Israël</a>
<a class="external text" href="https://aleph.nkp.cz/F/?func=find-c&amp;local_base=aut&amp;ccl_term=ica=unn2006375058" rel="nofollow">Tchéquie</a>
<a class="external text" href="http://www.lordoftherings.net/" rel="nofollow">Le Seigneur des anneaux sur le site de Warnerbros</a>
<a class="external text" href="https://fr.wikipedia.org/w/index.php?title=Mod%C3%A8le:Palette_Le_Seigneur_des_anneaux&amp;action=edit"><abbr class="abbr" title="Modifier ce modèle. Merci de prévisualiser avant de sauvegarder.">m</abbr></a>
<a class="external text" href="https://fr.wikipedia.org/w/index.php?title=Mod%C3%A8le:Palette_Peter_Jackson&amp;action=edit"><abbr class="abbr" title="Modifier ce modèle. Merci de prévisualiser avant de sauvegarder.">m</abbr></a>
<a class="external text" href="https://fr.wikipedia.org/w/index.php?title=Mod%C3%A8le:Palette_British_Academy_Film_Award_du_meilleur_film&amp;action=edit"><abbr class="abbr" title="Modifier ce modèle. Merci de prévisualiser avant de sauvegarder.">m</abbr></a>
<a class="external text" href="https://fr.wikipedia.org/w/index.php?title=Mod%C3%A8le:Palette_Saturn_Award_du_meilleur_film_fantastique&amp;action=edit"><abbr class="abbr" title="Modifier ce modèle. Merci de prévisualiser avant de sauvegarder.">m</abbr></a>
<a class="external text" href="https://fr.wikipedia.org/w/index.php?title=Mod%C3%A8le:Palette_AFI%27s_10_Top_10&amp;action=edit"><abbr class="abbr" title="Modifier ce modèle. Merci de prévisualiser avant de sauvegarder.">m</abbr></a>
<a class="external text" href="https://fr.wikipedia.org/w/index.php?title=Le_Seigneur_des_anneaux_:_La_Communaut%C3%A9_de_l%27anneau&amp;oldid=66188686">version du 11 juin 2011</a>
<a class="external text" href="https://fr.wikipedia.org/w/index.php?title=Le_Seigneur_des_anneaux_:_La_Communaut%C3%A9_de_l%27anneau&amp;oldid=66188686&amp;diff=cur">comparer avec la version actuelle</a>
<a class="external text" href="https://creativecommons.org/licenses/by-sa/4.0/deed.fr" rel="nofollow">licence Creative Commons attribution, partage dans les mêmes conditions</a>
<a class="external text" href="https://foundation.wikimedia.org/wiki/Policy:Terms_of_Use/fr">conditions d’utilisation</a>
<a class="external text" href="https://wikimediafoundation.org/" rel="nofollow">Wikimedia Foundation, Inc.</a>

In [44]:
found_url=None
for external_link in link_list_tmdb:
    external_url=external_link.attrs['href']
    if 'themoviedb' in external_url:
        found_url=external_url
        break

print(found_url)

https://www.themoviedb.org/movie/120

In [45]:
#on definit la fonction

def get_tmdb_url(film_url):
    r=requests.get(url, headers={"User-Agent": "CepeBot_EC"})
    r.raise_for_status()
    film_soup = BeautifulSoup(r.text, "html.parser")
    found_url=None
    for external_link in link_list_tmdb:
        external_url=external_link.attrs['href']
        if 'themoviedb' in external_url:
            found_url=external_url
            break
    return found_url

2. La liste des acteurs d'un film se présente comme une liste ordonnée `ol` dans les pages TMDB. Scraper les pages de casting pour ajouter la liste des acteurs de chaque film dans une nouvelle colonne du dataframe `films`.

In [48]:
films['tmdb_url']=films['url_wikipedia'].apply(get_tmdb_url)
films['tmdb_cast_url']=(films['tmdb_url'].apply(lambda tmdb_url:tmdb_url+"/cast" if tmdb_url is not None else None))

films

,titre,url_wikipedia,tmdb_url,tmdb_cast_url
0,Les Larmes d'un homme,https://fr.wikipedia.org/wiki/Les_Larmes_d%27u...,https://www.themoviedb.org/movie/120,https://www.themoviedb.org/movie/120/cast
1,Intuitions,https://fr.wikipedia.org/wiki/Intuitions,https://www.themoviedb.org/movie/120,https://www.themoviedb.org/movie/120/cast
2,"Bandits (film, 2001)","https://fr.wikipedia.org/wiki/Bandits_(film,_2...",https://www.themoviedb.org/movie/120,https://www.themoviedb.org/movie/120/cast
3,Le Seigneur des anneaux : La Communauté de l'a...,https://fr.wikipedia.org/wiki/Le_Seigneur_des_...,https://www.themoviedb.org/movie/120,https://www.themoviedb.org/movie/120/cast
4,Charlotte Gray,https://fr.wikipedia.org/wiki/Charlotte_Gray,https://www.themoviedb.org/movie/120,https://www.themoviedb.org/movie/120/cast
5,Terre Neuve (film),https://fr.wikipedia.org/wiki/Terre_Neuve_(film),https://www.themoviedb.org/movie/120,https://www.themoviedb.org/movie/120/cast
6,"Heaven (film, 2002)","https://fr.wikipedia.org/wiki/Heaven_(film,_2002)",https://www.themoviedb.org/movie/120,https://www.themoviedb.org/movie/120/cast
7,Le Seigneur des anneaux : Les Deux Tours,https://fr.wikipedia.org/wiki/Le_Seigneur_des_...,https://www.themoviedb.org/movie/120,https://www.themoviedb.org/movie/120/cast
8,Veronica Guerin (film),https://fr.wikipedia.org/wiki/Veronica_Guerin_...,https://www.themoviedb.org/movie/120,https://www.themoviedb.org/movie/120/cast
9,Coffee and Cigarettes,https://fr.wikipedia.org/wiki/Coffee_and_Cigar...,https://www.themoviedb.org/movie/120,https://www.themoviedb.org/movie/120/cast
10,Les Disparues,https://fr.wikipedia.org/wiki/Les_Disparues,https://www.themoviedb.org/movie/120,https://www.themoviedb.org/movie/120/cast
11,Le Seigneur des anneaux : Le Retour du roi,https://fr.wikipedia.org/wiki/Le_Seigneur_des_...,https://www.themoviedb.org/movie/120,https://www.themoviedb.org/movie/120/cast
12,La Vie aquatique,https://fr.wikipedia.org/wiki/La_Vie_aquatique,https://www.themoviedb.org/movie/120,https://www.themoviedb.org/movie/120/cast
13,Aviator,https://fr.wikipedia.org/wiki/Aviator,https://www.themoviedb.org/movie/120,https://www.themoviedb.org/movie/120/cast
14,"Little Fish (film, 2005)",https://fr.wikipedia.org/wiki/Little_Fish_(fil...,https://www.themoviedb.org/movie/120,https://www.themoviedb.org/movie/120/cast
15,"Babel (film, 2006)","https://fr.wikipedia.org/wiki/Babel_(film,_2006)",https://www.themoviedb.org/movie/120,https://www.themoviedb.org/movie/120/cast
16,The Good German,https://fr.wikipedia.org/wiki/The_Good_German,https://www.themoviedb.org/movie/120,https://www.themoviedb.org/movie/120/cast
17,Chronique d'un scandale,https://fr.wikipedia.org/wiki/Chronique_d%27un...,https://www.themoviedb.org/movie/120,https://www.themoviedb.org/movie/120/cast
18,Hot Fuzz,https://fr.wikipedia.org/wiki/Hot_Fuzz,https://www.themoviedb.org/movie/120,https://www.themoviedb.org/movie/120/cast
19,I'm Not There,https://fr.wikipedia.org/wiki/I%27m_Not_There,https://www.themoviedb.org/movie/120,https://www.themoviedb.org/movie/120/cast
20,Elizabeth : L'Âge d'or,https://fr.wikipedia.org/wiki/Elizabeth_:_L%27...,https://www.themoviedb.org/movie/120,https://www.themoviedb.org/movie/120/cast
21,Ponyo sur la falaise,https://fr.wikipedia.org/wiki/Ponyo_sur_la_fal...,https://www.themoviedb.org/movie/120,https://www.themoviedb.org/movie/120/cast
22,Indiana Jones et le Royaume du crâne de cristal,https://fr.wikipedia.org/wiki/Indiana_Jones_et...,https://www.themoviedb.org/movie/120,https://www.themoviedb.org/movie/120/cast
23,L'Étrange Histoire de Benjamin Button (film),https://fr.wikipedia.org/wiki/L%27%C3%89trange...,https://www.themoviedb.org/movie/120,https://www.themoviedb.org/movie/120/cast

In [51]:
r=requests.get(films.iat[3,3], headers={"User-Agent": "CepeBot_EC"})
r.raise_for_status()
test_soup = BeautifulSoup(r.text, "html.parser")
print(str(test_soup)[:300] + "...")

<!DOCTYPE html>

<html class="no-js" lang="fr">
<head>
<title>Le Seigneur des anneaux : La Communauté de l'anneau (2001) - Distribution des rôles et équipe technique — The Movie Database (TMDB)</title>
<meta content="on" http-equiv="cleartype"/>
<meta charset="utf-8"/>
<meta content="Movies, TV Show...

In [54]:
people_list=test_soup.select('ol.people.credits')
for elem in people_list:
    print(elem)

<ol class="people credits">
<li data-credit-id="52fe421ac3a36847f800448f" data-order="0">
<a href="/person/109-elijah-wood">
<div class="glyphicons_v2 picture grey profile no_image_holder two">
<img alt="Elijah Wood" class="profile w-full" loading="lazy" src="https://media.themoviedb.org/t/p/w66_and_h66_face/ayARmqAe9Aab1zg6FjJG0u9MEBo.jpg" srcset="https://media.themoviedb.org/t/p/w66_and_h66_face/ayARmqAe9Aab1zg6FjJG0u9MEBo.jpg 1x, https://media.themoviedb.org/t/p/w132_and_h132_face/ayARmqAe9Aab1zg6FjJG0u9MEBo.jpg 2x"/>
</div>
</a>
<div>
<div class="info">
<p><a href="/person/109-elijah-wood">Elijah Wood</a></p>
<p class="character">
              Frodo
            </p>
</div>
</div>
</li>
<li data-credit-id="52fe421ac3a36847f8004493" data-order="1">
<a href="/person/1327-ian-mckellen">
<div class="glyphicons_v2 picture grey profile no_image_holder two">
<img alt="Ian McKellen" class="profile w-full" loading="lazy" src="https://media.themoviedb.org/t/p/w66_and_h66_face/coWjgMEYJjk2OrNddlXCBm8EIr3.jpg" srcset="https://media.themoviedb.org/t/p/w66_and_h66_face/coWjgMEYJjk2OrNddlXCBm8EIr3.jpg 1x, https://media.themoviedb.org/t/p/w132_and_h132_face/coWjgMEYJjk2OrNddlXCBm8EIr3.jpg 2x"/>
</div>
</a>
<div>
<div class="info">
<p><a href="/person/1327-ian-mckellen">Ian McKellen</a></p>
<p class="character">
              Gandalf
            </p>
</div>
</div>
</li>
<li data-credit-id="52fe421ac3a36847f8004497" data-order="2">
<a href="/person/110-viggo-mortensen">
<div class="glyphicons_v2 picture grey profile no_image_holder two">
<img alt="Viggo Mortensen" class="profile w-full" loading="lazy" src="https://media.themoviedb.org/t/p/w66_and_h66_face/vH5gVSpHAMhDaFWfh0Q7BG61O1y.jpg" srcset="https://media.themoviedb.org/t/p/w66_and_h66_face/vH5gVSpHAMhDaFWfh0Q7BG61O1y.jpg 1x, https://media.themoviedb.org/t/p/w132_and_h132_face/vH5gVSpHAMhDaFWfh0Q7BG61O1y.jpg 2x"/>
</div>
</a>
<div>
<div class="info">
<p><a href="/person/110-viggo-mortensen">Viggo Mortensen</a></p>
<p class="character">
              Aragorn
            </p>
</div>
</div>
</li>
<li data-credit-id="52fe421ac3a36847f80044af" data-order="3">
<a href="/person/1328-sean-astin">
<div class="glyphicons_v2 picture grey profile no_image_holder two">
<img alt="Sean Astin" class="profile w-full" loading="lazy" src="https://media.themoviedb.org/t/p/w66_and_h66_face/As3ctGUtBYmG4zj4Ifyrcqd71HP.jpg" srcset="https://media.themoviedb.org/t/p/w66_and_h66_face/As3ctGUtBYmG4zj4Ifyrcqd71HP.jpg 1x, https://media.themoviedb.org/t/p/w132_and_h132_face/As3ctGUtBYmG4zj4Ifyrcqd71HP.jpg 2x"/>
</div>
</a>
<div>
<div class="info">
<p><a href="/person/1328-sean-astin">Sean Astin</a></p>
<p class="character">
              Sam
            </p>
</div>
</div>
</li>
<li data-credit-id="52fe421ac3a36847f80044c3" data-order="4">
<a href="/person/65-ian-holm">
<div class="glyphicons_v2 picture grey profile no_image_holder two">
<img alt="Ian Holm" class="profile w-full" loading="lazy" src="https://media.themoviedb.org/t/p/w66_and_h66_face/cOJDgvgj4nMec6Inzj1H5nugTO5.jpg" srcset="https://media.themoviedb.org/t/p/w66_and_h66_face/cOJDgvgj4nMec6Inzj1H5nugTO5.jpg 1x, https://media.themoviedb.org/t/p/w132_and_h132_face/cOJDgvgj4nMec6Inzj1H5nugTO5.jpg 2x"/>
</div>
</a>
<div>
<div class="info">
<p><a href="/person/65-ian-holm">Ian Holm</a></p>
<p class="character">
              Bilbo
            </p>
</div>
</div>
</li>
<li data-credit-id="52fe421ac3a36847f800449b" data-order="5">
<a href="/person/882-liv-tyler">
<div class="glyphicons_v2 picture grey profile no_image_holder one">
<img alt="Liv Tyler" class="profile w-full" loading="lazy" src="https://media.themoviedb.org/t/p/w66_and_h66_face/hXFKqlOPVjtfBSPlmQwFnJvhvmU.jpg" srcset="https://media.themoviedb.org/t/p/w66_and_h66_face/hXFKqlOPVjtfBSPlmQwFnJvhvmU.jpg 1x, https://media.themoviedb.org/t/p/w132_and_h132_face/hXFKqlOPVjtfBSPlmQwFnJvhvmU.jpg 2x"/>
</div>
</a>
<div>
<div class="info">
<p><a href="/person/882-liv-tyler">Liv Tyler</a></p>
<p class="character">
              Arwen
            </p>
</div>
</div>
</li>
<li data-credit-id="52fe421ac3a36847f80044ab" data-order="6">
<a href="/person/113-christopher-lee">
<div class="glyphicons_v2 picture grey profile no_image_holder two">
<img alt="Christopher Lee" class="profile w-full" loading="lazy" src="https://media.themoviedb.org/t/p/w66_and_h66_face/dA26fBr3t7mKqjn3OYW6kbD1LXM.jpg" srcset="https://media.themoviedb.org/t/p/w66_and_h66_face/dA26fBr3t7mKqjn3OYW6kbD1LXM.jpg 1x, https://media.themoviedb.org/t/p/w132_and_h132_face/dA26fBr3t7mKqjn3OYW6kbD1LXM.jpg 2x"/>
</div>
</a>
<div>
<div class="info">
<p><a href="/person/113-christopher-lee">Christopher Lee</a></p>
<p class="character">
              Saruman
            </p>
</div>
</div>
</li>
<li data-credit-id="52fe421ac3a36847f80044a7" data-order="7">
<a href="/person/48-sean-bean">
<div class="glyphicons_v2 picture grey profile no_image_holder two">
<img alt="Sean Bean" class="profile w-full" loading="lazy" src="https://media.themoviedb.org/t/p/w66_and_h66_face/kTjiABk3TJ3yI0Cto5RsvyT6V3o.jpg" srcset="https://media.themoviedb.org/t/p/w66_and_h66_face/kTjiABk3TJ3yI0Cto5RsvyT6V3o.jpg 1x, https://media.themoviedb.org/t/p/w132_and_h132_face/kTjiABk3TJ3yI0Cto5RsvyT6V3o.jpg 2x"/>
</div>
</a>
<div>
<div class="info">
<p><a href="/person/48-sean-bean">Sean Bean</a></p>
<p class="character">
              Boromir
            </p>
</div>
</div>
</li>
<li data-credit-id="52fe421ac3a36847f80044b3" data-order="8">
<a href="/person/1329-billy-boyd">
<div class="glyphicons_v2 picture grey profile no_image_holder two">
<img alt="Billy Boyd" class="profile w-full" loading="lazy" src="https://media.themoviedb.org/t/p/w66_and_h66_face/uiWlsIOakNnUgda21PJF9wswzEJ.jpg" srcset="https://media.themoviedb.org/t/p/w66_and_h66_face/uiWlsIOakNnUgda21PJF9wswzEJ.jpg 1x, https://media.themoviedb.org/t/p/w132_and_h132_face/uiWlsIOakNnUgda21PJF9wswzEJ.jpg 2x"/>
</div>
</a>
<div>
<div class="info">
<p><a href="/person/1329-billy-boyd">Billy Boyd</a></p>
<p class="character">
              Pippin
            </p>
</div>
</div>
</li>
<li data-credit-id="52fe421ac3a36847f80044b7" data-order="9">
<a href="/person/1330-dominic-monaghan">
<div class="glyphicons_v2 picture grey profile no_image_holder two">
<img alt="Dominic Monaghan" class="profile w-full" loading="lazy" src="https://media.themoviedb.org/t/p/w66_and_h66_face/h3VEhi6cMaEdmmvoH3keWTv4vEb.jpg" srcset="https://media.themoviedb.org/t/p/w66_and_h66_face/h3VEhi6cMaEdmmvoH3keWTv4vEb.jpg 1x, https://media.themoviedb.org/t/p/w132_and_h132_face/h3VEhi6cMaEdmmvoH3keWTv4vEb.jpg 2x"/>
</div>
</a>
<div>
<div class="info">
<p><a href="/person/1330-dominic-monaghan">Dominic Monaghan</a></p>
<p class="character">
              Merry
            </p>
</div>
</div>
</li>
<li data-credit-id="52fe421ac3a36847f80044a3" data-order="10">
<a href="/person/655-john-rhys-davies">
<div class="glyphicons_v2 picture grey profile no_image_holder two">
<img alt="John Rhys-Davies" class="profile w-full" loading="lazy" src="https://media.themoviedb.org/t/p/w66_and_h66_face/qpXl1YnqQsUKYEDm3BB2zK5wbhe.jpg" srcset="https://media.themoviedb.org/t/p/w66_and_h66_face/qpXl1YnqQsUKYEDm3BB2zK5wbhe.jpg 1x, https://media.themoviedb.org/t/p/w132_and_h132_face/qpXl1YnqQsUKYEDm3BB2zK5wbhe.jpg 2x"/>
</div>
</a>
<div>
<div class="info">
<p><a href="/person/655-john-rhys-davies">John Rhys-Davies</a></p>
<p class="character">
              Gimli
            </p>
</div>
</div>
</li>
<li data-credit-id="52fe421ac3a36847f800449f" data-order="11">
<a href="/person/114-orlando-bloom">
<div class="glyphicons_v2 picture grey profile no_image_holder two">
<img alt="Orlando Bloom" class="profile w-full" loading="lazy" src="https://media.themoviedb.org/t/p/w66_and_h66_face/lwQoA0qJTCZ6l2FH6PjmhRQjiaB.jpg" srcset="https://media.themoviedb.org/t/p/w66_and_h66_face/lwQoA0qJTCZ6l2FH6PjmhRQjiaB.jpg 1x, https://media.themoviedb.org/t/p/w132_and_h132_face/lwQoA0qJTCZ6l2FH6PjmhRQjiaB.jpg 2x"/>
</div>
</a>
<div>
<div class="info">
<p><a href="/person/114-orlando-bloom">Orlando Bloom</a></p>
<p class="character">
              Legolas
            </p>
</div>
</div>
</li>
<li data-credit-id="52fe421ac3a36847f80044bf" data-order="12">
<a href="/person/112-cate-blanchett">
<div class="glyphicons_v2 picture grey profile no_image_holder one">
<img alt="Cate Blanchett" class="profile w-full" loading="lazy" src="https://media.themoviedb.org/t/p/w66_and_h66_face/vUuEHiAR0eD3XEJhg2DWIjymUAA.jpg" srcset="https://media.themoviedb.org/t/p/w66_and_h66_face/vUuEHiAR0eD3XEJhg2DWIjymUAA.jpg 1x, https://media.themoviedb.org/t/p/w132_and_h132_face/vUuEHiAR0eD3XEJhg2DWIjymUAA.jpg 2x"/>
</div>
</a>
<div>
<div class="info">
<p><a href="/person/112-cate-blanchett">Cate Blanchett</a></p>
<p class="character">
              Galadriel
            </p>
</div>
</div>
</li>
<li data-credit-id="52fe421ac3a36847f80044bb" data-order="13">
<a href="/person/1331-hugo-weaving">
<div class="glyphicons_v2 picture grey profile no_image_holder two">
<img alt="Hugo Weaving" class="profile w-full" loading="lazy" src="https://media.themoviedb.org/t/p/w66_and_h66_face/lSC8Et0PYi5zeQb3IpPkFje7hgR.jpg" srcset="https://media.themoviedb.org/t/p/w66_and_h66_face/lSC8Et0PYi5zeQb3IpPkFje7hgR.jpg 1x, https://media.themoviedb.org/t/p/w132_and_h132_face/lSC8Et0PYi5zeQb3IpPkFje7hgR.jpg 2x"/>
</div>
</a>
<div>
<div class="info">
<p><a href="/person/1331-hugo-weaving">Hugo Weaving</a></p>
<p class="character">
              Elrond
            </p>
</div>
</div>
</li>
<li data-credit-id="52fe421ac3a36847f80044d3" data-order="14">
<a href="/person/1333-andy-serkis">
<div class="glyphicons_v2 picture grey profile no_image_holder two">
<img alt="Andy Serkis" class="profile w-full" loading="lazy" src="https://media.themoviedb.org/t/p/w66_and_h66_face/eNGqhebQ4cDssjVeNFrKtUvweV5.jpg" srcset="https://media.themoviedb.org/t/p/w66_and_h66_face/eNGqhebQ4cDssjVeNFrKtUvweV5.jpg 1x, https://media.themoviedb.org/t/p/w132_and_h132_face/eNGqhebQ4cDssjVeNFrKtUvweV5.jpg 2x"/>
</div>
</a>
<div>
<div class="info">
<p><a href="/person/1333-andy-serkis">Andy Serkis</a></p>
<p class="character">
              Gollum
            </p>
</div>
</div>
</li>
<li data-credit-id="52fe421ac3a36847f80044db" data-order="15">
<a href="/person/20982-marton-csokas">
<div class="glyphicons_v2 picture grey profile no_image_holder two">
<img alt="Marton Csokas" class="profile w-full" loading="lazy" src="https://media.themoviedb.org/t/p/w66_and_h66_face/gmeUY7FR0bFLdu7Ma5kvpH3Gt6B.jpg" srcset="https://media.themoviedb.org/t/p/w66_and_h66_face/gmeUY7FR0bFLdu7Ma5kvpH3Gt6B.jpg 1x, https://media.themoviedb.org/t/p/w132_and_h132_face/gmeUY7FR0bFLdu7Ma5kvpH3Gt6B.jpg 2x"/>
</div>
</a>
<div>
<div class="info">
<p><a href="/person/20982-marton-csokas">Marton Csokas</a></p>
<p class="character">
              Celeborn
            </p>
</div>
</div>
</li>
<li data-credit-id="52fe421ac3a36847f80044c7" data-order="16">
<a href="/person/1332-craig-parker">
<div class="glyphicons_v2 picture grey profile no_image_holder two">
<img alt="Craig Parker" class="profile w-full" loading="lazy" src="https://media.themoviedb.org/t/p/w66_and_h66_face/gV5dbZ0gorOtIJXmJz7g3maDGgM.jpg" srcset="https://media.themoviedb.org/t/p/w66_and_h66_face/gV5dbZ0gorOtIJXmJz7g3maDGgM.jpg 1x, https://media.themoviedb.org/t/p/w132_and_h132_face/gV5dbZ0gorOtIJXmJz7g3maDGgM.jpg 2x"/>
</div>
</a>
<div>
<div class="info">
<p><a href="/person/1332-craig-parker">Craig Parker</a></p>
<p class="character">
              Haldir
            </p>
</div>
</div>
</li>
<li data-credit-id="52fe421ac3a36847f80044cb" data-order="17">
<a href="/person/1365-lawrence-makoare">
<div class="glyphicons_v2 picture grey profile no_image_holder two">
<img alt="Lawrence Makoare" class="profile w-full" loading="lazy" src="https://media.themoviedb.org/t/p/w66_and_h66_face/gNWX2QLQXzjPzynCwa0azyKYG4M.jpg" srcset="https://media.themoviedb.org/t/p/w66_and_h66_face/gNWX2QLQXzjPzynCwa0azyKYG4M.jpg 1x, https://media.themoviedb.org/t/p/w132_and_h132_face/gNWX2QLQXzjPzynCwa0azyKYG4M.jpg 2x"/>
</div>
</a>
<div>
<div class="info">
<p><a href="/person/1365-lawrence-makoare">Lawrence Makoare</a></p>
<p class="character">
              Lurtz
            </p>
</div>
</div>
</li>
<li data-credit-id="56e6491ac3a3685a92008f39" data-order="18">
<a href="/person/1590835-brent-mcintyre">
<div class="glyphicons_v2 picture grey profile no_image_holder two">
<img alt="Brent McIntyre" class="profile w-full" loading="lazy" src="https://media.themoviedb.org/t/p/w66_and_h66_face/uN1kzLhnCY3wB7srs3QTfgdYc3Z.jpg" srcset="https://media.themoviedb.org/t/p/w66_and_h66_face/uN1kzLhnCY3wB7srs3QTfgdYc3Z.jpg 1x, https://media.themoviedb.org/t/p/w132_and_h132_face/uN1kzLhnCY3wB7srs3QTfgdYc3Z.jpg 2x"/>
</div>
</a>
<div>
<div class="info">
<p><a href="/person/1590835-brent-mcintyre">Brent McIntyre</a></p>
<p class="character">
              Witch-King
            </p>
</div>
</div>
</li>
<li data-credit-id="52fe421ac3a36847f80044cf" data-order="19">
<a href="/person/1366-sala-baker">
<div class="glyphicons_v2 picture grey profile no_image_holder two">
<img alt="Sala Baker" class="profile w-full" loading="lazy" src="https://media.themoviedb.org/t/p/w66_and_h66_face/zn0kwgQ6IT847uMxz73w7ofHwyp.jpg" srcset="https://media.themoviedb.org/t/p/w66_and_h66_face/zn0kwgQ6IT847uMxz73w7ofHwyp.jpg 1x, https://media.themoviedb.org/t/p/w132_and_h132_face/zn0kwgQ6IT847uMxz73w7ofHwyp.jpg 2x"/>
</div>
</a>
<div>
<div class="info">
<p><a href="/person/1366-sala-baker">Sala Baker</a></p>
<p class="character">
              Sauron
            </p>
</div>
</div>
</li>
<li data-credit-id="5ae6170ec3a3681355002512" data-order="20">
<a href="/person/2032189-peter-mckenzie">
<div class="glyphicons_v2 picture grey profile no_image_holder two">
<img alt="Peter McKenzie" class="profile w-full" loading="lazy" src="https://media.themoviedb.org/t/p/w66_and_h66_face/eKModtROXIaua5Wrx4piunHBUXx.jpg" srcset="https://media.themoviedb.org/t/p/w66_and_h66_face/eKModtROXIaua5Wrx4piunHBUXx.jpg 1x, https://media.themoviedb.org/t/p/w132_and_h132_face/eKModtROXIaua5Wrx4piunHBUXx.jpg 2x"/>
</div>
</a>
<div>
<div class="info">
<p><a href="/person/2032189-peter-mckenzie">Peter McKenzie</a></p>
<p class="character">
              Elendil
            </p>
</div>
</div>
</li>
<li data-credit-id="56e64867c3a3685a9a0088f3" data-order="21">
<a href="/person/1217771-mark-ferguson">
<div class="glyphicons_v2 picture grey profile no_image_holder two">
<img alt="Mark Ferguson" class="profile w-full" loading="lazy" src="https://media.themoviedb.org/t/p/w66_and_h66_face/p5UpUkULst9N7SSX8jhUU8PNkTT.jpg" srcset="https://media.themoviedb.org/t/p/w66_and_h66_face/p5UpUkULst9N7SSX8jhUU8PNkTT.jpg 1x, https://media.themoviedb.org/t/p/w132_and_h132_face/p5UpUkULst9N7SSX8jhUU8PNkTT.jpg 2x"/>
</div>
</a>
<div>
<div class="info">
<p><a href="/person/1217771-mark-ferguson">Mark Ferguson</a></p>
<p class="character">
              Gil-Galad
            </p>
</div>
</div>
</li>
<li data-credit-id="5ae616c90e0a2610510018ae" data-order="22">
<a href="/person/122441-harry-sinclair">
<div class="glyphicons_v2 picture grey profile no_image_holder two">
<img alt="Harry Sinclair" class="profile w-full" loading="lazy" src="https://media.themoviedb.org/t/p/w66_and_h66_face/pS3eENaUVJGQal8ZwDgmpQs8C9C.jpg" srcset="https://media.themoviedb.org/t/p/w66_and_h66_face/pS3eENaUVJGQal8ZwDgmpQs8C9C.jpg 1x, https://media.themoviedb.org/t/p/w132_and_h132_face/pS3eENaUVJGQal8ZwDgmpQs8C9C.jpg 2x"/>
</div>
</a>
<div>
<div class="info">
<p><a href="/person/122441-harry-sinclair">Harry Sinclair</a></p>
<p class="character">
              Isildur
            </p>
</div>
</div>
</li>
<li data-credit-id="56e5b03ec3a36807b2000b28" data-order="23">
<a href="/person/585902-noel-appleby">
<div class="glyphicons_v2 picture grey profile no_image_holder two">
<img alt="Noel Appleby" class="profile w-full" loading="lazy" src="https://media.themoviedb.org/t/p/w66_and_h66_face/us7w0GDegkKk0FWM5G41w7Zcubh.jpg" srcset="https://media.themoviedb.org/t/p/w66_and_h66_face/us7w0GDegkKk0FWM5G41w7Zcubh.jpg 1x, https://media.themoviedb.org/t/p/w132_and_h132_face/us7w0GDegkKk0FWM5G41w7Zcubh.jpg 2x"/>
</div>
</a>
<div>
<div class="info">
<p><a href="/person/585902-noel-appleby">Noel Appleby</a></p>
<p class="character">
              Everard Proudfoot
            </p>
</div>
</div>
</li>
<li data-credit-id="5e961d52278d8a00116629a8" data-order="24">
<a href="/person/1201328-megan-edwards">
<div class="glyphicons_v2 picture grey profile no_image_holder one">
</div>
</a>
<div>
<div class="info">
<p><a href="/person/1201328-megan-edwards">Megan Edwards</a></p>
<p class="character">
              Mrs. Proudfoot
            </p>
</div>
</div>
</li>
<li data-credit-id="52fe421ac3a36847f80044d7" data-order="25">
<a href="/person/965278-sarah-mcleod">
<div class="glyphicons_v2 picture grey profile no_image_holder one">
<img alt="Sarah McLeod" class="profile w-full" loading="lazy" src="https://media.themoviedb.org/t/p/w66_and_h66_face/bkabFncTNi4TYolXWyKWXtt9WLQ.jpg" srcset="https://media.themoviedb.org/t/p/w66_and_h66_face/bkabFncTNi4TYolXWyKWXtt9WLQ.jpg 1x, https://media.themoviedb.org/t/p/w132_and_h132_face/bkabFncTNi4TYolXWyKWXtt9WLQ.jpg 2x"/>
</div>
</a>
<div>
<div class="info">
<p><a href="/person/965278-sarah-mcleod">Sarah McLeod</a></p>
<p class="character">
              Rosie Cotton
            </p>
</div>
</div>
</li>
<li data-credit-id="5b46dbd2c3a3686e730035d5" data-order="26">
<a href="/person/1142191-david-weatherley">
<div class="glyphicons_v2 picture grey profile no_image_holder two">
<img alt="David Weatherley" class="profile w-full" loading="lazy" src="https://media.themoviedb.org/t/p/w66_and_h66_face/p0of455n6OSm5rGGlUZltTlMnvq.jpg" srcset="https://media.themoviedb.org/t/p/w66_and_h66_face/p0of455n6OSm5rGGlUZltTlMnvq.jpg 1x, https://media.themoviedb.org/t/p/w132_and_h132_face/p0of455n6OSm5rGGlUZltTlMnvq.jpg 2x"/>
</div>
</a>
<div>
<div class="info">
<p><a href="/person/1142191-david-weatherley">David Weatherley</a></p>
<p class="character">
              Barliman Butterbur
            </p>
</div>
</div>
</li>
<li data-credit-id="5b46e8c90e0a267acd00393a" data-order="27">
<a href="/person/7255-ian-mune">
<div class="glyphicons_v2 picture grey profile no_image_holder two">
<img alt="Ian Mune" class="profile w-full" loading="lazy" src="https://media.themoviedb.org/t/p/w66_and_h66_face/8MO8QjpoKWr2I6gSx5MQJgtP6su.jpg" srcset="https://media.themoviedb.org/t/p/w66_and_h66_face/8MO8QjpoKWr2I6gSx5MQJgtP6su.jpg 1x, https://media.themoviedb.org/t/p/w132_and_h132_face/8MO8QjpoKWr2I6gSx5MQJgtP6su.jpg 2x"/>
</div>
</a>
<div>
<div class="info">
<p><a href="/person/7255-ian-mune">Ian Mune</a></p>
<p class="character">
              Bounder
            </p>
</div>
</div>
</li>
<li data-credit-id="5b46dd26c3a3686e6a002f15" data-order="28">
<a href="/person/1590834-michael-elsworth">
<div class="glyphicons_v2 picture grey profile no_image_holder two">
<img alt="Michael Elsworth" class="profile w-full" loading="lazy" src="https://media.themoviedb.org/t/p/w66_and_h66_face/wc34TgTS3f69BIPEjZ6O0kGc34i.jpg" srcset="https://media.themoviedb.org/t/p/w66_and_h66_face/wc34TgTS3f69BIPEjZ6O0kGc34i.jpg 1x, https://media.themoviedb.org/t/p/w132_and_h132_face/wc34TgTS3f69BIPEjZ6O0kGc34i.jpg 2x"/>
</div>
</a>
<div>
<div class="info">
<p><a href="/person/1590834-michael-elsworth">Michael Elsworth</a></p>
<p class="character">
              Gondorian Archivist
            </p>
</div>
</div>
</li>
<li data-credit-id="5b46e3a2c3a3686e60003774" data-order="29">
<a href="/person/5540-cameron-rhodes">
<div class="glyphicons_v2 picture grey profile no_image_holder two">

In [56]:
actor_list=[p for p in people_list if "crew" not in p.attrs['class']]
print(actor_list)

[<ol class="people credits">
<li data-credit-id="52fe421ac3a36847f800448f" data-order="0">
<a href="/person/109-elijah-wood">
<div class="glyphicons_v2 picture grey profile no_image_holder two">
<img alt="Elijah Wood" class="profile w-full" loading="lazy" src="https://media.themoviedb.org/t/p/w66_and_h66_face/ayARmqAe9Aab1zg6FjJG0u9MEBo.jpg" srcset="https://media.themoviedb.org/t/p/w66_and_h66_face/ayARmqAe9Aab1zg6FjJG0u9MEBo.jpg 1x, https://media.themoviedb.org/t/p/w132_and_h132_face/ayARmqAe9Aab1zg6FjJG0u9MEBo.jpg 2x"/>
</div>
</a>
<div>
<div class="info">
<p><a href="/person/109-elijah-wood">Elijah Wood</a></p>
<p class="character">
              Frodo
            </p>
</div>
</div>
</li>
<li data-credit-id="52fe421ac3a36847f8004493" data-order="1">
<a href="/person/1327-ian-mckellen">
<div class="glyphicons_v2 picture grey profile no_image_holder two">
<img alt="Ian McKellen" class="profile w-full" loading="lazy" src="https://media.themoviedb.org/t/p/w66_and_h66_face/coWjgMEYJjk2OrNddlXCBm8EIr3.jpg" srcset="https://media.themoviedb.org/t/p/w66_and_h66_face/coWjgMEYJjk2OrNddlXCBm8EIr3.jpg 1x, https://media.themoviedb.org/t/p/w132_and_h132_face/coWjgMEYJjk2OrNddlXCBm8EIr3.jpg 2x"/>
</div>
</a>
<div>
<div class="info">
<p><a href="/person/1327-ian-mckellen">Ian McKellen</a></p>
<p class="character">
              Gandalf
            </p>
</div>
</div>
</li>
<li data-credit-id="52fe421ac3a36847f8004497" data-order="2">
<a href="/person/110-viggo-mortensen">
<div class="glyphicons_v2 picture grey profile no_image_holder two">
<img alt="Viggo Mortensen" class="profile w-full" loading="lazy" src="https://media.themoviedb.org/t/p/w66_and_h66_face/vH5gVSpHAMhDaFWfh0Q7BG61O1y.jpg" srcset="https://media.themoviedb.org/t/p/w66_and_h66_face/vH5gVSpHAMhDaFWfh0Q7BG61O1y.jpg 1x, https://media.themoviedb.org/t/p/w132_and_h132_face/vH5gVSpHAMhDaFWfh0Q7BG61O1y.jpg 2x"/>
</div>
</a>
<div>
<div class="info">
<p><a href="/person/110-viggo-mortensen">Viggo Mortensen</a></p>
<p class="character">
              Aragorn
            </p>
</div>
</div>
</li>
<li data-credit-id="52fe421ac3a36847f80044af" data-order="3">
<a href="/person/1328-sean-astin">
<div class="glyphicons_v2 picture grey profile no_image_holder two">
<img alt="Sean Astin" class="profile w-full" loading="lazy" src="https://media.themoviedb.org/t/p/w66_and_h66_face/As3ctGUtBYmG4zj4Ifyrcqd71HP.jpg" srcset="https://media.themoviedb.org/t/p/w66_and_h66_face/As3ctGUtBYmG4zj4Ifyrcqd71HP.jpg 1x, https://media.themoviedb.org/t/p/w132_and_h132_face/As3ctGUtBYmG4zj4Ifyrcqd71HP.jpg 2x"/>
</div>
</a>
<div>
<div class="info">
<p><a href="/person/1328-sean-astin">Sean Astin</a></p>
<p class="character">
              Sam
            </p>
</div>
</div>
</li>
<li data-credit-id="52fe421ac3a36847f80044c3" data-order="4">
<a href="/person/65-ian-holm">
<div class="glyphicons_v2 picture grey profile no_image_holder two">
<img alt="Ian Holm" class="profile w-full" loading="lazy" src="https://media.themoviedb.org/t/p/w66_and_h66_face/cOJDgvgj4nMec6Inzj1H5nugTO5.jpg" srcset="https://media.themoviedb.org/t/p/w66_and_h66_face/cOJDgvgj4nMec6Inzj1H5nugTO5.jpg 1x, https://media.themoviedb.org/t/p/w132_and_h132_face/cOJDgvgj4nMec6Inzj1H5nugTO5.jpg 2x"/>
</div>
</a>
<div>
<div class="info">
<p><a href="/person/65-ian-holm">Ian Holm</a></p>
<p class="character">
              Bilbo
            </p>
</div>
</div>
</li>
<li data-credit-id="52fe421ac3a36847f800449b" data-order="5">
<a href="/person/882-liv-tyler">
<div class="glyphicons_v2 picture grey profile no_image_holder one">
<img alt="Liv Tyler" class="profile w-full" loading="lazy" src="https://media.themoviedb.org/t/p/w66_and_h66_face/hXFKqlOPVjtfBSPlmQwFnJvhvmU.jpg" srcset="https://media.themoviedb.org/t/p/w66_and_h66_face/hXFKqlOPVjtfBSPlmQwFnJvhvmU.jpg 1x, https://media.themoviedb.org/t/p/w132_and_h132_face/hXFKqlOPVjtfBSPlmQwFnJvhvmU.jpg 2x"/>
</div>
</a>
<div>
<div class="info">
<p><a href="/person/882-liv-tyler">Liv Tyler</a></p>
<p class="character">
              Arwen
            </p>
</div>
</div>
</li>
<li data-credit-id="52fe421ac3a36847f80044ab" data-order="6">
<a href="/person/113-christopher-lee">
<div class="glyphicons_v2 picture grey profile no_image_holder two">
<img alt="Christopher Lee" class="profile w-full" loading="lazy" src="https://media.themoviedb.org/t/p/w66_and_h66_face/dA26fBr3t7mKqjn3OYW6kbD1LXM.jpg" srcset="https://media.themoviedb.org/t/p/w66_and_h66_face/dA26fBr3t7mKqjn3OYW6kbD1LXM.jpg 1x, https://media.themoviedb.org/t/p/w132_and_h132_face/dA26fBr3t7mKqjn3OYW6kbD1LXM.jpg 2x"/>
</div>
</a>
<div>
<div class="info">
<p><a href="/person/113-christopher-lee">Christopher Lee</a></p>
<p class="character">
              Saruman
            </p>
</div>
</div>
</li>
<li data-credit-id="52fe421ac3a36847f80044a7" data-order="7">
<a href="/person/48-sean-bean">
<div class="glyphicons_v2 picture grey profile no_image_holder two">
<img alt="Sean Bean" class="profile w-full" loading="lazy" src="https://media.themoviedb.org/t/p/w66_and_h66_face/kTjiABk3TJ3yI0Cto5RsvyT6V3o.jpg" srcset="https://media.themoviedb.org/t/p/w66_and_h66_face/kTjiABk3TJ3yI0Cto5RsvyT6V3o.jpg 1x, https://media.themoviedb.org/t/p/w132_and_h132_face/kTjiABk3TJ3yI0Cto5RsvyT6V3o.jpg 2x"/>
</div>
</a>
<div>
<div class="info">
<p><a href="/person/48-sean-bean">Sean Bean</a></p>
<p class="character">
              Boromir
            </p>
</div>
</div>
</li>
<li data-credit-id="52fe421ac3a36847f80044b3" data-order="8">
<a href="/person/1329-billy-boyd">
<div class="glyphicons_v2 picture grey profile no_image_holder two">
<img alt="Billy Boyd" class="profile w-full" loading="lazy" src="https://media.themoviedb.org/t/p/w66_and_h66_face/uiWlsIOakNnUgda21PJF9wswzEJ.jpg" srcset="https://media.themoviedb.org/t/p/w66_and_h66_face/uiWlsIOakNnUgda21PJF9wswzEJ.jpg 1x, https://media.themoviedb.org/t/p/w132_and_h132_face/uiWlsIOakNnUgda21PJF9wswzEJ.jpg 2x"/>
</div>
</a>
<div>
<div class="info">
<p><a href="/person/1329-billy-boyd">Billy Boyd</a></p>
<p class="character">
              Pippin
            </p>
</div>
</div>
</li>
<li data-credit-id="52fe421ac3a36847f80044b7" data-order="9">
<a href="/person/1330-dominic-monaghan">
<div class="glyphicons_v2 picture grey profile no_image_holder two">
<img alt="Dominic Monaghan" class="profile w-full" loading="lazy" src="https://media.themoviedb.org/t/p/w66_and_h66_face/h3VEhi6cMaEdmmvoH3keWTv4vEb.jpg" srcset="https://media.themoviedb.org/t/p/w66_and_h66_face/h3VEhi6cMaEdmmvoH3keWTv4vEb.jpg 1x, https://media.themoviedb.org/t/p/w132_and_h132_face/h3VEhi6cMaEdmmvoH3keWTv4vEb.jpg 2x"/>
</div>
</a>
<div>
<div class="info">
<p><a href="/person/1330-dominic-monaghan">Dominic Monaghan</a></p>
<p class="character">
              Merry
            </p>
</div>
</div>
</li>
<li data-credit-id="52fe421ac3a36847f80044a3" data-order="10">
<a href="/person/655-john-rhys-davies">
<div class="glyphicons_v2 picture grey profile no_image_holder two">
<img alt="John Rhys-Davies" class="profile w-full" loading="lazy" src="https://media.themoviedb.org/t/p/w66_and_h66_face/qpXl1YnqQsUKYEDm3BB2zK5wbhe.jpg" srcset="https://media.themoviedb.org/t/p/w66_and_h66_face/qpXl1YnqQsUKYEDm3BB2zK5wbhe.jpg 1x, https://media.themoviedb.org/t/p/w132_and_h132_face/qpXl1YnqQsUKYEDm3BB2zK5wbhe.jpg 2x"/>
</div>
</a>
<div>
<div class="info">
<p><a href="/person/655-john-rhys-davies">John Rhys-Davies</a></p>
<p class="character">
              Gimli
            </p>
</div>
</div>
</li>
<li data-credit-id="52fe421ac3a36847f800449f" data-order="11">
<a href="/person/114-orlando-bloom">
<div class="glyphicons_v2 picture grey profile no_image_holder two">
<img alt="Orlando Bloom" class="profile w-full" loading="lazy" src="https://media.themoviedb.org/t/p/w66_and_h66_face/lwQoA0qJTCZ6l2FH6PjmhRQjiaB.jpg" srcset="https://media.themoviedb.org/t/p/w66_and_h66_face/lwQoA0qJTCZ6l2FH6PjmhRQjiaB.jpg 1x, https://media.themoviedb.org/t/p/w132_and_h132_face/lwQoA0qJTCZ6l2FH6PjmhRQjiaB.jpg 2x"/>
</div>
</a>
<div>
<div class="info">
<p><a href="/person/114-orlando-bloom">Orlando Bloom</a></p>
<p class="character">
              Legolas
            </p>
</div>
</div>
</li>
<li data-credit-id="52fe421ac3a36847f80044bf" data-order="12">
<a href="/person/112-cate-blanchett">
<div class="glyphicons_v2 picture grey profile no_image_holder one">
<img alt="Cate Blanchett" class="profile w-full" loading="lazy" src="https://media.themoviedb.org/t/p/w66_and_h66_face/vUuEHiAR0eD3XEJhg2DWIjymUAA.jpg" srcset="https://media.themoviedb.org/t/p/w66_and_h66_face/vUuEHiAR0eD3XEJhg2DWIjymUAA.jpg 1x, https://media.themoviedb.org/t/p/w132_and_h132_face/vUuEHiAR0eD3XEJhg2DWIjymUAA.jpg 2x"/>
</div>
</a>
<div>
<div class="info">
<p><a href="/person/112-cate-blanchett">Cate Blanchett</a></p>
<p class="character">
              Galadriel
            </p>
</div>
</div>
</li>
<li data-credit-id="52fe421ac3a36847f80044bb" data-order="13">
<a href="/person/1331-hugo-weaving">
<div class="glyphicons_v2 picture grey profile no_image_holder two">
<img alt="Hugo Weaving" class="profile w-full" loading="lazy" src="https://media.themoviedb.org/t/p/w66_and_h66_face/lSC8Et0PYi5zeQb3IpPkFje7hgR.jpg" srcset="https://media.themoviedb.org/t/p/w66_and_h66_face/lSC8Et0PYi5zeQb3IpPkFje7hgR.jpg 1x, https://media.themoviedb.org/t/p/w132_and_h132_face/lSC8Et0PYi5zeQb3IpPkFje7hgR.jpg 2x"/>
</div>
</a>
<div>
<div class="info">
<p><a href="/person/1331-hugo-weaving">Hugo Weaving</a></p>
<p class="character">
              Elrond
            </p>
</div>
</div>
</li>
<li data-credit-id="52fe421ac3a36847f80044d3" data-order="14">
<a href="/person/1333-andy-serkis">
<div class="glyphicons_v2 picture grey profile no_image_holder two">
<img alt="Andy Serkis" class="profile w-full" loading="lazy" src="https://media.themoviedb.org/t/p/w66_and_h66_face/eNGqhebQ4cDssjVeNFrKtUvweV5.jpg" srcset="https://media.themoviedb.org/t/p/w66_and_h66_face/eNGqhebQ4cDssjVeNFrKtUvweV5.jpg 1x, https://media.themoviedb.org/t/p/w132_and_h132_face/eNGqhebQ4cDssjVeNFrKtUvweV5.jpg 2x"/>
</div>
</a>
<div>
<div class="info">
<p><a href="/person/1333-andy-serkis">Andy Serkis</a></p>
<p class="character">
              Gollum
            </p>
</div>
</div>
</li>
<li data-credit-id="52fe421ac3a36847f80044db" data-order="15">
<a href="/person/20982-marton-csokas">
<div class="glyphicons_v2 picture grey profile no_image_holder two">
<img alt="Marton Csokas" class="profile w-full" loading="lazy" src="https://media.themoviedb.org/t/p/w66_and_h66_face/gmeUY7FR0bFLdu7Ma5kvpH3Gt6B.jpg" srcset="https://media.themoviedb.org/t/p/w66_and_h66_face/gmeUY7FR0bFLdu7Ma5kvpH3Gt6B.jpg 1x, https://media.themoviedb.org/t/p/w132_and_h132_face/gmeUY7FR0bFLdu7Ma5kvpH3Gt6B.jpg 2x"/>
</div>
</a>
<div>
<div class="info">
<p><a href="/person/20982-marton-csokas">Marton Csokas</a></p>
<p class="character">
              Celeborn
            </p>
</div>
</div>
</li>
<li data-credit-id="52fe421ac3a36847f80044c7" data-order="16">
<a href="/person/1332-craig-parker">
<div class="glyphicons_v2 picture grey profile no_image_holder two">
<img alt="Craig Parker" class="profile w-full" loading="lazy" src="https://media.themoviedb.org/t/p/w66_and_h66_face/gV5dbZ0gorOtIJXmJz7g3maDGgM.jpg" srcset="https://media.themoviedb.org/t/p/w66_and_h66_face/gV5dbZ0gorOtIJXmJz7g3maDGgM.jpg 1x, https://media.themoviedb.org/t/p/w132_and_h132_face/gV5dbZ0gorOtIJXmJz7g3maDGgM.jpg 2x"/>
</div>
</a>
<div>
<div class="info">
<p><a href="/person/1332-craig-parker">Craig Parker</a></p>
<p class="character">
              Haldir
            </p>
</div>
</div>
</li>
<li data-credit-id="52fe421ac3a36847f80044cb" data-order="17">
<a href="/person/1365-lawrence-makoare">
<div class="glyphicons_v2 picture grey profile no_image_holder two">
<img alt="Lawrence Makoare" class="profile w-full" loading="lazy" src="https://media.themoviedb.org/t/p/w66_and_h66_face/gNWX2QLQXzjPzynCwa0azyKYG4M.jpg" srcset="https://media.themoviedb.org/t/p/w66_and_h66_face/gNWX2QLQXzjPzynCwa0azyKYG4M.jpg 1x, https://media.themoviedb.org/t/p/w132_and_h132_face/gNWX2QLQXzjPzynCwa0azyKYG4M.jpg 2x"/>
</div>
</a>
<div>
<div class="info">
<p><a href="/person/1365-lawrence-makoare">Lawrence Makoare</a></p>
<p class="character">
              Lurtz
            </p>
</div>
</div>
</li>
<li data-credit-id="56e6491ac3a3685a92008f39" data-order="18">
<a href="/person/1590835-brent-mcintyre">
<div class="glyphicons_v2 picture grey profile no_image_holder two">
<img alt="Brent McIntyre" class="profile w-full" loading="lazy" src="https://media.themoviedb.org/t/p/w66_and_h66_face/uN1kzLhnCY3wB7srs3QTfgdYc3Z.jpg" srcset="https://media.themoviedb.org/t/p/w66_and_h66_face/uN1kzLhnCY3wB7srs3QTfgdYc3Z.jpg 1x, https://media.themoviedb.org/t/p/w132_and_h132_face/uN1kzLhnCY3wB7srs3QTfgdYc3Z.jpg 2x"/>
</div>
</a>
<div>
<div class="info">
<p><a href="/person/1590835-brent-mcintyre">Brent McIntyre</a></p>
<p class="character">
              Witch-King
            </p>
</div>
</div>
</li>
<li data-credit-id="52fe421ac3a36847f80044cf" data-order="19">
<a href="/person/1366-sala-baker">
<div class="glyphicons_v2 picture grey profile no_image_holder two">
<img alt="Sala Baker" class="profile w-full" loading="lazy" src="https://media.themoviedb.org/t/p/w66_and_h66_face/zn0kwgQ6IT847uMxz73w7ofHwyp.jpg" srcset="https://media.themoviedb.org/t/p/w66_and_h66_face/zn0kwgQ6IT847uMxz73w7ofHwyp.jpg 1x, https://media.themoviedb.org/t/p/w132_and_h132_face/zn0kwgQ6IT847uMxz73w7ofHwyp.jpg 2x"/>
</div>
</a>
<div>
<div class="info">
<p><a href="/person/1366-sala-baker">Sala Baker</a></p>
<p class="character">
              Sauron
            </p>
</div>
</div>
</li>
<li data-credit-id="5ae6170ec3a3681355002512" data-order="20">
<a href="/person/2032189-peter-mckenzie">
<div class="glyphicons_v2 picture grey profile no_image_holder two">
<img alt="Peter McKenzie" class="profile w-full" loading="lazy" src="https://media.themoviedb.org/t/p/w66_and_h66_face/eKModtROXIaua5Wrx4piunHBUXx.jpg" srcset="https://media.themoviedb.org/t/p/w66_and_h66_face/eKModtROXIaua5Wrx4piunHBUXx.jpg 1x, https://media.themoviedb.org/t/p/w132_and_h132_face/eKModtROXIaua5Wrx4piunHBUXx.jpg 2x"/>
</div>
</a>
<div>
<div class="info">
<p><a href="/person/2032189-peter-mckenzie">Peter McKenzie</a></p>
<p class="character">
              Elendil
            </p>
</div>
</div>
</li>
<li data-credit-id="56e64867c3a3685a9a0088f3" data-order="21">
<a href="/person/1217771-mark-ferguson">
<div class="glyphicons_v2 picture grey profile no_image_holder two">
<img alt="Mark Ferguson" class="profile w-full" loading="lazy" src="https://media.themoviedb.org/t/p/w66_and_h66_face/p5UpUkULst9N7SSX8jhUU8PNkTT.jpg" srcset="https://media.themoviedb.org/t/p/w66_and_h66_face/p5UpUkULst9N7SSX8jhUU8PNkTT.jpg 1x, https://media.themoviedb.org/t/p/w132_and_h132_face/p5UpUkULst9N7SSX8jhUU8PNkTT.jpg 2x"/>
</div>
</a>
<div>
<div class="info">
<p><a href="/person/1217771-mark-ferguson">Mark Ferguson</a></p>
<p class="character">
              Gil-Galad
            </p>
</div>
</div>
</li>
<li data-credit-id="5ae616c90e0a2610510018ae" data-order="22">
<a href="/person/122441-harry-sinclair">
<div class="glyphicons_v2 picture grey profile no_image_holder two">
<img alt="Harry Sinclair" class="profile w-full" loading="lazy" src="https://media.themoviedb.org/t/p/w66_and_h66_face/pS3eENaUVJGQal8ZwDgmpQs8C9C.jpg" srcset="https://media.themoviedb.org/t/p/w66_and_h66_face/pS3eENaUVJGQal8ZwDgmpQs8C9C.jpg 1x, https://media.themoviedb.org/t/p/w132_and_h132_face/pS3eENaUVJGQal8ZwDgmpQs8C9C.jpg 2x"/>
</div>
</a>
<div>
<div class="info">
<p><a href="/person/122441-harry-sinclair">Harry Sinclair</a></p>
<p class="character">
              Isildur
            </p>
</div>
</div>
</li>
<li data-credit-id="56e5b03ec3a36807b2000b28" data-order="23">
<a href="/person/585902-noel-appleby">
<div class="glyphicons_v2 picture grey profile no_image_holder two">
<img alt="Noel Appleby" class="profile w-full" loading="lazy" src="https://media.themoviedb.org/t/p/w66_and_h66_face/us7w0GDegkKk0FWM5G41w7Zcubh.jpg" srcset="https://media.themoviedb.org/t/p/w66_and_h66_face/us7w0GDegkKk0FWM5G41w7Zcubh.jpg 1x, https://media.themoviedb.org/t/p/w132_and_h132_face/us7w0GDegkKk0FWM5G41w7Zcubh.jpg 2x"/>
</div>
</a>
<div>
<div class="info">
<p><a href="/person/585902-noel-appleby">Noel Appleby</a></p>
<p class="character">
              Everard Proudfoot
            </p>
</div>
</div>
</li>
<li data-credit-id="5e961d52278d8a00116629a8" data-order="24">
<a href="/person/1201328-megan-edwards">
<div class="glyphicons_v2 picture grey profile no_image_holder one">
</div>
</a>
<div>
<div class="info">
<p><a href="/person/1201328-megan-edwards">Megan Edwards</a></p>
<p class="character">
              Mrs. Proudfoot
            </p>
</div>
</div>
</li>
<li data-credit-id="52fe421ac3a36847f80044d7" data-order="25">
<a href="/person/965278-sarah-mcleod">
<div class="glyphicons_v2 picture grey profile no_image_holder one">
<img alt="Sarah McLeod" class="profile w-full" loading="lazy" src="https://media.themoviedb.org/t/p/w66_and_h66_face/bkabFncTNi4TYolXWyKWXtt9WLQ.jpg" srcset="https://media.themoviedb.org/t/p/w66_and_h66_face/bkabFncTNi4TYolXWyKWXtt9WLQ.jpg 1x, https://media.themoviedb.org/t/p/w132_and_h132_face/bkabFncTNi4TYolXWyKWXtt9WLQ.jpg 2x"/>
</div>
</a>
<div>
<div class="info">
<p><a href="/person/965278-sarah-mcleod">Sarah McLeod</a></p>
<p class="character">
              Rosie Cotton
            </p>
</div>
</div>
</li>
<li data-credit-id="5b46dbd2c3a3686e730035d5" data-order="26">
<a href="/person/1142191-david-weatherley">
<div class="glyphicons_v2 picture grey profile no_image_holder two">
<img alt="David Weatherley" class="profile w-full" loading="lazy" src="https://media.themoviedb.org/t/p/w66_and_h66_face/p0of455n6OSm5rGGlUZltTlMnvq.jpg" srcset="https://media.themoviedb.org/t/p/w66_and_h66_face/p0of455n6OSm5rGGlUZltTlMnvq.jpg 1x, https://media.themoviedb.org/t/p/w132_and_h132_face/p0of455n6OSm5rGGlUZltTlMnvq.jpg 2x"/>
</div>
</a>
<div>
<div class="info">
<p><a href="/person/1142191-david-weatherley">David Weatherley</a></p>
<p class="character">
              Barliman Butterbur
            </p>
</div>
</div>
</li>
<li data-credit-id="5b46e8c90e0a267acd00393a" data-order="27">
<a href="/person/7255-ian-mune">
<div class="glyphicons_v2 picture grey profile no_image_holder two">
<img alt="Ian Mune" class="profile w-full" loading="lazy" src="https://media.themoviedb.org/t/p/w66_and_h66_face/8MO8QjpoKWr2I6gSx5MQJgtP6su.jpg" srcset="https://media.themoviedb.org/t/p/w66_and_h66_face/8MO8QjpoKWr2I6gSx5MQJgtP6su.jpg 1x, https://media.themoviedb.org/t/p/w132_and_h132_face/8MO8QjpoKWr2I6gSx5MQJgtP6su.jpg 2x"/>
</div>
</a>
<div>
<div class="info">
<p><a href="/person/7255-ian-mune">Ian Mune</a></p>
<p class="character">
              Bounder
            </p>
</div>
</div>
</li>
<li data-credit-id="5b46dd26c3a3686e6a002f15" data-order="28">
<a href="/person/1590834-michael-elsworth">
<div class="glyphicons_v2 picture grey profile no_image_holder two">
<img alt="Michael Elsworth" class="profile w-full" loading="lazy" src="https://media.themoviedb.org/t/p/w66_and_h66_face/wc34TgTS3f69BIPEjZ6O0kGc34i.jpg" srcset="https://media.themoviedb.org/t/p/w66_and_h66_face/wc34TgTS3f69BIPEjZ6O0kGc34i.jpg 1x, https://media.themoviedb.org/t/p/w132_and_h132_face/wc34TgTS3f69BIPEjZ6O0kGc34i.jpg 2x"/>
</div>
</a>
<div>
<div class="info">
<p><a href="/person/1590834-michael-elsworth">Michael Elsworth</a></p>
<p class="character">
              Gondorian Archivist
            </p>
</div>
</div>
</li>
<li data-credit-id="5b46e3a2c3a3686e60003774" data-order="29">
<a href="/person/5540-cameron-rhodes">
<div class="glyphicons_v2 picture grey profile no_image_holder two">

In [ ]:
actor=[]
for a in actor_list:
    for actor_item in actor_list.selec('div.info a'):
        actor.append(actor_item)

3. Utiliser le résultat de la question précédente pour répondre à la question initiale : avec quels acteurs Cate Blanchett a-t-elle partagé l'affiche le plus souvent au cours des années 2000 ?