# Notebook 6 : MongoDB

In [ ]:
# Décommenter la ligne suivante pour installer pymongo
#%pip install pymongo

Collecting pymongo
  Downloading pymongo-4.16.0-cp313-cp313-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl.metadata (10.0 kB)
Collecting dnspython<3.0.0,>=2.6.1 (from pymongo)
  Downloading dnspython-2.8.0-py3-none-any.whl.metadata (5.7 kB)
Downloading pymongo-4.16.0-cp313-cp313-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl (2.0 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.0/2.0 MB 11.1 MB/s  0:00:00 eta 0:00:01
Downloading dnspython-2.8.0-py3-none-any.whl (331 kB)
Installing collected packages: dnspython, pymongo
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2/2 [pymongo]m1/2 [pymongo]
Successfully installed dnspython-2.8.0 pymongo-4.16.0
Note: you may need to restart the kernel to use updated packages.

In [2]:
import json

import pandas as pd
import pymongo

client = pymongo.MongoClient(
    'mongodb://user-echatillon-ensae:seypzil1ipvk005wzk1q@mongodb-0.mongodb-headless:27017,mongodb-1.mongodb-headless:27017/defaultdb?authSource=defaultdb'
)

db = client.defaultdb

## Planètes de Star Wars

Nous considérons ici les données des planètes de *Star Wars* exportées à la fin du *Notebook 4*. Le fichier `planets.json` est également disponible dans le dossier des jeux de données.

1. Accéder à une collection `planets` et s'assurer qu'elle est vide grâce à la méthode `count_documents`.

In [ ]:
planets=db['planets']
planets.drop()
planets.count_documents({})

0

2. Importer les données des planètes dans la collection `planets`.

In [ ]:

df_planet=pd.read_json('planets.ndjson',lines=True)
df_planet.head(7)

,edited,climate,surface_water,name,diameter,rotation_period,created,terrain,gravity,orbital_period,population,residents,films,url
0,2014-12-20T20:58:18.411Z,arid,1,Tatooine,10465,23,2014-12-09T13:50:49.641Z,desert,1 standard,304,200000,[],[],/api/planets/1
1,2014-12-20T20:58:18.420Z,temperate,40,Alderaan,12500,24,2014-12-10T11:35:48.479Z,"grasslands, mountains",1 standard,364,2000000000,[],[],/api/planets/2
2,2014-12-20T20:58:18.421Z,"temperate, tropical",8,Yavin IV,10200,24,2014-12-10T11:37:19.144Z,"jungle, rainforests",1 standard,4818,1000,[],[],/api/planets/3
3,2014-12-20T20:58:18.423Z,frozen,100,Hoth,7200,23,2014-12-10T11:39:13.934Z,"tundra, ice caves, mountain ranges",1.1 standard,549,unknown,[],[],/api/planets/4
4,2014-12-20T20:58:18.425Z,murky,8,Dagobah,8900,23,2014-12-10T11:42:22.590Z,"swamp, jungles",N/A,341,unknown,[],[],/api/planets/5
5,2014-12-20T20:58:18.427Z,temperate,0,Bespin,118000,12,2014-12-10T11:43:55.240Z,gas giant,"1.5 (surface), 1 standard (Cloud City)",5110,6000000,[],[],/api/planets/6
6,2014-12-20T20:58:18.429Z,temperate,8,Endor,4900,18,2014-12-10T11:50:29.349Z,"forests, mountains, lakes",0.85 standard,402,30000000,[],[],/api/planets/7

In [ ]:
result = planets.insert_many(df_planet.to_dict(orient="records")) # Insertion
print(f"{len(result.inserted_ids)} planetes ajoutées")

60 cartes ajoutées

3. Exporter l'ensemble des planètes sans l'identifiant `_id` dans un dataframe à l'aide du résultat de la méthode `find`.

In [15]:
list_planet = planets.find(
    projection={"_id": False}
    )

pd.DataFrame(list_planet).head(5)

,edited,climate,surface_water,name,diameter,rotation_period,created,terrain,gravity,orbital_period,population,residents,films,url
0,2014-12-20T20:58:18.411Z,arid,1,Tatooine,10465,23,2014-12-09T13:50:49.641Z,desert,1 standard,304,200000,[],[],/api/planets/1
1,2014-12-20T20:58:18.420Z,temperate,40,Alderaan,12500,24,2014-12-10T11:35:48.479Z,"grasslands, mountains",1 standard,364,2000000000,[],[],/api/planets/2
2,2014-12-20T20:58:18.421Z,"temperate, tropical",8,Yavin IV,10200,24,2014-12-10T11:37:19.144Z,"jungle, rainforests",1 standard,4818,1000,[],[],/api/planets/3
3,2014-12-20T20:58:18.423Z,frozen,100,Hoth,7200,23,2014-12-10T11:39:13.934Z,"tundra, ice caves, mountain ranges",1.1 standard,549,unknown,[],[],/api/planets/4
4,2014-12-20T20:58:18.425Z,murky,8,Dagobah,8900,23,2014-12-10T11:42:22.590Z,"swamp, jungles",N/A,341,unknown,[],[],/api/planets/5

4. Rechercher les planètes dont la période de rotation est égale à 25. Quel est le problème ? Combien y en a-t-il ?

In [20]:
list_planet = planets.find(
    filter={"rotation_period": '25'},
    projection={"_id": False}
    )

pd.DataFrame(list_planet).head(7)

,edited,climate,surface_water,name,diameter,rotation_period,created,terrain,gravity,orbital_period,population,residents,films,url
0,2014-12-20T20:58:18.449Z,"temperate, moist",unknown,Cato Neimoidia,0,25,2014-12-10T13:46:28.704Z,"mountains, fields, forests, rock arches",1 standard,278,10000000,[],[],/api/planets/18
1,2014-12-20T20:58:18.456Z,temperate,70,Corellia,11000,25,2014-12-10T16:49:12.453Z,"plains, urban, hills, forests",1 standard,329,3000000000,[],[],/api/planets/22
2,2014-12-20T20:58:18.461Z,temperate,unknown,Dantooine,9830,25,2014-12-10T17:23:29.896Z,"oceans, savannas, mountains, grasslands",1 standard,378,1000,[],[],/api/planets/25
3,2014-12-20T20:58:18.468Z,arid,unknown,Trandosha,0,25,2014-12-15T12:53:47.695Z,"mountains, seas, grasslands, deserts",0.62 standard,371,42000000,[],[],/api/planets/29
4,2014-12-20T20:58:18.491Z,temperate,unknown,Haruun Kal,10120,25,2014-12-20T10:12:28.980Z,"toxic cloudsea, plateaus, volcanoes",0.98,383,705300,[],[],/api/planets/42

5. Même question mais en limitant la réponse aux clés `name`, `rotation_period`, `orbital_period` et `diameter`.

In [21]:
list_planet = planets.find(
    filter={"rotation_period": '25'},
    projection={"_id": False,'name':True,'rotation_period':True,'orbital_period':True,'diameter':True}
    )

pd.DataFrame(list_planet).head(7)

             name diameter rotation_period orbital_period
0  Cato Neimoidia        0              25            278
1        Corellia    11000              25            329
2       Dantooine     9830              25            378
3       Trandosha        0              25            371
4      Haruun Kal    10120              25            383

6. Trier les planètes du résultat précédent par diamètre décroissant. Quel est le problème ?

In [27]:
list_planet = planets.find(
    filter={"rotation_period": '25'},
    projection={"_id": False,'name':True,'rotation_period':True,'orbital_period':True,'diameter':True}
    )

df=pd.DataFrame(list_planet)
df["diameter"] = pd.to_numeric(df["diameter"], errors="coerce")
df.sort_values(by=['diameter'], ascending=False).head(7)

             name  diameter rotation_period orbital_period
1        Corellia     11000              25            329
4      Haruun Kal     10120              25            383
2       Dantooine      9830              25            378
0  Cato Neimoidia         0              25            278
3       Trandosha         0              25            371

7. Vider la collection et importer à nouveau les données mais en faisant les corrections suivantes au préalable (un dataframe intermédiaire pourra être utilisé pour manipuler les données avant leur insertion) :
- convertir les valeurs numériques (gérer les cas `unknown`),
- supprimer les variables `created`, `edited`, `films`, `gravity`, `residents` et `url`.
- transformer les variables `climate` et `terrain` en listes de chaînes de caractères plutôt qu'une longue chaîne séparée par des virgules.

In [35]:
import numpy as np

planets=db['planets']
planets.drop()
planets.count_documents({})
df_planet=pd.read_json('planets.ndjson',lines=True)

#convertir valeur numerique
for colu in ['rotation_period','diameter','orbital_period','population','surface_water']:
    df_planet[colu] =df_planet[colu].replace("unknown", np.nan)
    df_planet[colu] = pd.to_numeric(df_planet[colu], errors="coerce")



#suppression des colonnes
clean_df=df_planet.drop(columns=['created','edited','gravity','residents'])

clean_df['climate']=clean_df['climate'].str.split(', ')
clean_df['terrain']=clean_df['terrain'].str.split(', ')
clean_df.head(7)
result = planets.insert_many(clean_df.to_dict(orient="records")) # Insertion
print(f"{len(result.inserted_ids)} planetes ajoutées")

60 planetes ajoutées

8. Reprendre la question 6 et vérifier que le résultat est maintenant correct.

In [37]:
list_planet = planets.find(
    filter={"rotation_period": 25},
    projection={"_id": False,'name':True,'rotation_period':True,'orbital_period':True,'diameter':True}
    )

pd.DataFrame(list_planet).sort_values(by=['diameter'], ascending=False).head(7)

             name  diameter  rotation_period  orbital_period
1        Corellia   11000.0             25.0           329.0
4      Haruun Kal   10120.0             25.0           383.0
2       Dantooine    9830.0             25.0           378.0
0  Cato Neimoidia       0.0             25.0           278.0
3       Trandosha       0.0             25.0           371.0

9. Extraire les planètes dont le nom commence par `T`.

In [38]:
list_planet = planets.find(
    filter={"name": {"$regex": "^T"}},
    projection={"_id": False}
    )

pd.DataFrame(list_planet).sort_values(by=['diameter'], ascending=False).head(7)

,climate,surface_water,name,diameter,rotation_period,terrain,orbital_period,population,films,url
4,[unknown],NaN,Tund,12190.0,48.0,"[barren, ash]",1770.0,0.0,[],/api/planets/41
0,[arid],1.0,Tatooine,10465.0,23.0,[desert],304.0,200000.0,[],/api/planets/1
2,[temperate],NaN,Toydaria,7900.0,21.0,"[swamps, lakes]",184.0,11000000.0,[],/api/planets/34
1,[arid],NaN,Trandosha,0.0,25.0,"[mountains, seas, grasslands, deserts]",371.0,42000000.0,[],/api/planets/29
3,[unknown],NaN,Troiken,NaN,NaN,"[desert, tundra, rainforests, mountains]",NaN,NaN,[],/api/planets/40
5,[unknown],NaN,Tholoth,NaN,NaN,[unknown],NaN,NaN,[],/api/planets/46

10. Extraire les planètes dont le diamètre est strictement supérieur à 10000 et où se trouvent des montagnes.

In [46]:
list_planet = planets.find(
    filter={"$and":[{"diameter": {"$gt": 10000}},{'terrain':{'$in':['mountains']}}]},
    projection={"_id": False}
    )

pd.DataFrame(list_planet).sort_values(by=['diameter'], ascending=False).head(7)

,climate,surface_water,name,diameter,rotation_period,terrain,orbital_period,population,films,url
6,"[arid, temperate, tropical]",NaN,Malastare,18880.0,26.0,"[swamps, deserts, jungles, mountains]",201.0,2.000000e+09,[],/api/planets/35
4,[hot],NaN,Saleucami,14920.0,26.0,"[caves, desert, mountains, volcanoes]",392.0,1.400000e+09,[],/api/planets/19
8,[temperate],25.0,Muunilinst,13800.0,28.0,"[plains, forests, hills, mountains]",412.0,5.000000e+09,[],/api/planets/57
5,[superheated],5.0,Sullust,12780.0,20.0,"[mountains, volcanoes, rocky deserts]",263.0,1.850000e+10,[],/api/planets/33
0,[temperate],40.0,Alderaan,12500.0,24.0,"[grasslands, mountains]",364.0,2.000000e+09,[],/api/planets/2
2,[temperate],NaN,Coruscant,12240.0,24.0,"[cityscape, mountains]",368.0,1.000000e+12,[],/api/planets/9
1,[temperate],12.0,Naboo,12120.0,26.0,"[grassy hills, swamps, forests, mountains]",312.0,4.500000e+09,[],/api/planets/8

11. Rechercher puis supprimer la planète dont le nom est `unknown`.

In [47]:
list_planet = planets.find(
    filter={"name": "unknown"},
    projection={"_id": False}
    )

pd.DataFrame(list_planet).sort_values(by=['diameter'], ascending=False).head(7)

,climate,surface_water,name,diameter,rotation_period,terrain,orbital_period,population,films,url
0,[unknown],NaN,unknown,0.0,0.0,[unknown],0.0,NaN,[],/api/planets/28

In [48]:
planets.delete_one({'name':'unknown'})

DeleteResult({'n': 1, 'opTime': {'ts': Timestamp(1775827597, 1), 't': 3}, 'electionId': ObjectId('7fffffff0000000000000003'), 'ok': 1.0, '$clusterTime': {'clusterTime': Timestamp(1775827597, 1), 'signature': {'hash': b'B \x1d\xca\x8e\xc1h\xe8\xc9\xc7a\\!+\x85\x83=\x91\xf6=', 'keyId': 7627061760993787906}}, 'operationTime': Timestamp(1775827597, 1)}, acknowledged=True)

In [49]:
list_planet = planets.find(
    filter={"name": "unknown"},
    projection={"_id": False}
    )

pd.DataFrame(list_planet).head(7)

Empty DataFrame
Columns: []
Index: []

12. Mettre en œuvre un pipeline d'agrégation qui calcule le nombre de planètes dans la collection. Verifier le résultat avec la méthode `count_documents`.

In [ ]:
list_planet.distinct(key="typename_name")

13. Mettre en œuvre un pipeline d'agrégation pour calculer le diamètre moyen et la somme des populations des planètes contenant des glaciers.